### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#102]
It would be nice to get a logo for this project. Traceur have just sorted one out, and I'm also putting a presentation together where it would be nice to have the two projects with logos on the same slide.

@addyosmani the image used for the ModuleLoader organisation, is that just random, or something being considered as a logo concept?

**Comment by douglasduteil** [comment]
? 
Did you find one you like @guybedford  ?

**Comment by guybedford** [comment]
No, but I guess the loader spec itself should really be the focus here, and this is just a polyfill, so not sure we need one.
