### ISSUE TITLE
Reload already loaded modules

### ISSUE THREAD

**Issue by wclr** [ModuleLoader/es6-module-loader#203]
Is it possible somehow to instruct System.js loader to dynamically load with (`System.import`) already loaded module (with all dependencies)?

**Comment by timbur** [comment]
Any progress on this?  If not, I'll put something together.

**Comment by whitecolor** [comment]
@timbur what progress? its working. 
```
System.delete('module')
System.import('module')
```

**Comment by timbur** [comment]
Does that reload all affected modules as well?

**Comment by whitecolor** [comment]
@timbur no ofource, if you want to do this you have to find out depended modueles and redefine them in correct order. I've implemented such reloader for myself but haven't published.

**Comment by timbur** [comment]
Good to know.  Thanks for the response!

**Comment by Qualphey** [comment]
I've made a test with hot realoading. This is the code

```
      SystemJS.import('test.js').then(function(m) {
        console.log(SystemJS.loads);
        SystemJS.delete('test.js');
        SystemJS.import('test.js').then(function(m) {
          console.log(SystemJS.loads);
        });;
      });
```

the source of the `test.js` file is just `console.log('testing..');`. The output is:

```
testing..
Object { http://localhost:9639/modules/test.js: Object }
Object { http://localhost:9639/modules/test.js: Object }
```
but I'm expecting the modules to be re-executed, so the output would be like so:

```
testing..
Object { http://localhost:9639/modules/test.js: Object }
testing..
Object { http://localhost:9639/modules/test.js: Object }
```
Did I miss something or I put my expectations too high? xO
