### ISSUE TITLE
Unable to import a module with System.import in nodejs.

### ISSUE THREAD

**Issue by trusktr** [ModuleLoader/es6-module-loader#271]
I'm trying to do this:

```
echo '{}' > package.json
npm install es6-module-loader
npm install infamous
vim test.js
```

test.js:

``` js
var System = require('es6-module-loader').System;

System.import('./node_modules/infamous/Cube').then(function(Mod) {
    console.log('hello', Mod.Cube);
});
```

then running `node test.js` results in no output to the console.

I also tried `System.import('infamous/Cube')` with no luck (much nicer without the `node_modules` in the path).

**Comment by trusktr** [comment]
I'm debating on what to do. So if I compile with traceur, then it would require traceur to in the environment. If I use 6to5, then it can compile to vanilla es5 without traceur, so it'd be easily compatible with browserify without es6ify. Any recommendation on which direction to go in?

**Comment by trusktr** [comment]
@guybedford K, I think I've come up with a consumable package.json. With jspm, the es6 modules are used. For browserify and webpack, the files get built to umd on install, but the es6 modules could be used or the src built to amd or cjs. For bower bower.json is symlinked to package.json, and no build happens when installing. I suppose bower users can use something like your `es6` loader for RequireJS, or they can build the modules manually in some build step with grunt or gulp? Any tips?

```
{
  "name": "infamous",
  "version": "0.0.11",
  "description": "A UI library.",
  "format": "es6",
  "main": "infamous.js",
  "scripts": {
    "test": "echo 'TODO: Test script' && exit 1",
    "clean": "rm -rf dist",
    "postinstall": "npm run build-umd",
    "build-umd": "6to5 src --source-maps --out-dir dist --modules umd",
    "build-cjs": "6to5 src --source-maps --out-dir dist --modules common",
    "build-amd": "6to5 src --source-maps --out-dir dist --modules amd",
    "build-global": "echo 'TODO: Global build' && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:infamous/infamous.git"
  },
  "keywords": [
    "user",
    "interface",
    "ui",
    "widgets",
    "widgets",
    "components",
    "gui",
    "touch",
    "mobile"
  ],
  "authors": [
    "Joseph Orbegoso Pea <joe@trusktr.io>"
  ],
  "license": "MPL",
  "dependencies": {
    "army-knife": "^0.0.4",
    "famous": "git+https://github.com/trusktr/famous.git#trusktr",
    "jss": "^0.10.1"
  },
  "devDependencies": {
    "6to5": "^2.4.3"
  },
  "bugs": {
    "url": "https://github.com/infamous/infamous/issues"
  },
  "homepage": "https://github.com/infamous/infamous",
  "author": ""
}
```

**Comment by guybedford** [comment]
@trusktr it is probably best to include the already-built sources when publishing for npm and webpack.

Why do you need UMD and not just CommonJS?

**Comment by guybedford** [comment]
@trusktr I suppose what I mean is that it is much easier to support Node and CommonJS than also trying to support globals, which reduces the portability tremendously.

If you advise a browser workflow through Node like Browserify or Webpack as expected, that makes things a lot easier I think?

**Comment by trusktr** [comment]
@guybedford The reason I put the build steps for UMD, AMD, and CJS is to make infamous as consumable as possible, that way, if for some reason someone wants to use AMD or UMD, they can. I changed the default build to CJS though.

As for Globals, I don't think of making each module global, but having an entry point requires every module so that is possible to do

```js
var infamous = require('infamous'); // f.e. A RequireJS shim made it global, but require it here anyways.
var Plane = infamous.Plane;
var PushMenuLayout = infamous.PushMenuLayout;
```

So the build script for the global would just be something like `browserify index.js -o global.js or similar`, where each module is CJS, but then the final object that required all the modules is attached to global. Would that reduce portability?

I agree, I'd prefer to use webpack, browserify, or jspm, but the global build could be published to a CDN so someone with no back-end nodejs experience can simply include a script tag in their page and start using the library without worrying about learning a tool yet.
