### ISSUE TITLE
Consider distributables

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#278]
With the addition of 6to5, we effectively get 4 loader variations, which is making the build files a bit too much.

It may be worth considering moving away from the approach of trying to have a single script, and instead just instruct users to include three scripts to make this work:

```html
<script src="promise-polyfill.js"></script>
<script src="es6-module-loader.js"></script>
<script src="es6-module-loader--traceur-parser.js"></script> <!-- or 6to5 -->
```

Further, it would then be quite nice if the `es6-module-loader.js` on its own contained none of the declarative linking code, making it a smaller size for production. The parser builds would then contain the duplicated declarative linking code, used for development only, but I don't see that as a problem.

Now just to do that full rewrite. Goal is to get this done before the end of Feb. Let's see how that goes...

**Comment by douglasduteil** [comment]
Looking forward for this :+1: 


> It may be worth considering moving away from the approach of trying to have a single script, and instead just instruct users to include three scripts to make this work:

Do you mean that you want to keep the inclusion of the `es6-module-loader` simple ? like one script to go ?
If it's the case I feel like the fact that it has multiple dependencies must be "hided" inside the script inclusion. The far more secure to keep a hand on it.
A pretty straightforward approach would be to add some attributes on the script like 

```html
<script
  src="es6-module-loader.js"
  data-promise-polyfill="RSVP"
  data-es6-compiler="6to5"
></script> 
```

What you think ?

**Comment by guybedford** [comment]
I think the above is just as much writing as having three script tags, so would rather not use syntax here.

**Comment by douglasduteil** [comment]
Alright (:

**Comment by guybedford** [comment]
Parser is small enough not to be an issue all combined after all.
