### ISSUE TITLE
IE8 issue with $__Object$getPrototypeOf

### ISSUE THREAD

**Issue by tracer99** [ModuleLoader/es6-module-loader#282]
Using es6-module-loader in steal 0.4

$__Object$getPrototypeOf returns null in IE8 causing       

    $__Object$getPrototypeOf(SystemLoader.prototype).constructor.call(this, options || {});

to fail.

**Comment by guybedford** [comment]
Thanks, I think this might be a steal issue?

**Comment by justinbmeyer** [comment]
This is ESML's code. @tracer99 can you point to this line in ESML?

**Comment by tracer99** [comment]
@justinbmeyer sorry, I don't understand what you're asking me to do.

**Comment by justinbmeyer** [comment]
@tracer99 yes, and where it is consumed.  Also, perhaps point to a fix.  Btw, do ES6ML's tests break in IE8?  If not, creating one that does would speed things along.

I can help you around 3pm CST if you need it.

**Comment by tracer99** [comment]
@justinbmeyer thanks. I will probably need help with the tests yes.

**Comment by guybedford** [comment]
`$__Object$getPrototypeOf` is not used anywhere in the ES6 Module Loader source?

**Comment by tracer99** [comment]
@guybedford 
I'm assuming because of the string-replace pattern in the Gruntfile.js it's not in the src folder but is in the dist folder.

**Comment by guybedford** [comment]
I don't think it is actually called anywhere in the dist file?

**Comment by tracer99** [comment]
You're right.

**Comment by matthewp** [comment]
This is generated by esnext.

**Comment by guybedford** [comment]
So this is why I created this Grunt rule for IE8 compatibility - https://github.com/ModuleLoader/es6-module-loader/blob/master/Gruntfile.js#L60.

**Comment by guybedford** [comment]
Closing for now, as the issue isn't in this current code.
