### ISSUE TITLE
Check source maps

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#293]
Sources seem to be duplicated with the `!eval` trick that was added, so I'm not sure if this is really the best thing to be doing, but it does seem to help source map displays.

It is worth looking into this again.

**Comment by guybedford** [comment]
The main issue seems to be that if there is just a `sourceMappingURL`, immediate execution doesn't seem to have loaded the source map yet so line debugging doesn't work.

If we add a `sourceURL` with the same name, all sources then become the transpiled source, not the original source.

So we need to create an indirect source with the `!eval` thing.

Not ideal, but I guess this is actually a browser bug? Definitely for re-evaluating as Browsers change.

**Comment by edrex** [comment]
Thanks for the explanation @guybedford. I guess people can get traces pointing to the original files in most cases by wrapping their main entry point with
```
window.setTimeout(() => { entry point code here}, 0)
```
in development.

**Comment by edrex** [comment]
The traces for sync exceptions in Firefox are kind of useless (they don't link to the `!eval` file).

```
"Potentially unhandled rejection [2] .execute@https://jspm.io/es6-module-loader@0.16.5.js line 1 > eval:12:1
g@https://jspm.io/es6-module-loader@0.16.5.js:1:20458
w@https://jspm.io/es6-module-loader@0.16.5.js:1:20850
b@https://jspm.io/es6-module-loader@0.16.5.js:1:20526
_@https://jspm.io/es6-module-loader@0.16.5.js:1:20407
x.prototype.import/</<@https://jspm.io/es6-module-loader@0.16.5.js:1:22734
D@https://jspm.io/es6-module-loader@0.16.5.js:1:7437
I@https://jspm.io/es6-module-loader@0.16.5.js:1:7071
[7]</</</</O.prototype.when@https://jspm.io/es6-module-loader@0.16.5.js:1:10745
[7]</</</</w.prototype.run@https://jspm.io/es6-module-loader@0.16.5.js:1:9779
[3]</</</e.prototype._drain@https://jspm.io/es6-module-loader@0.16.5.js:1:1725
e/this.drain@https://jspm.io/es6-module-loader@0.16.5.js:1:1392
t@https://jspm.io/es6-module-loader@0.16.5.js:1:3302
"```

**Comment by guybedford** [comment]
The trick is unavoidable. It's the difference between transpiled and untranspiled source.
