### ISSUE TITLE
Can we System.register inside a System.import 

### ISSUE THREAD

**Issue by douglasduteil** [ModuleLoader/es6-module-loader#300]
Going after the no definition of `__moduleAddress` on my config.
I end up writing down a failing test like : 

```js
// Le test
it.only('should support module name meta', function (done) {
  System.import('test/loader/moduleNameInSystem')
    .then(function (m) {
      expect(m.name).to.be.equal('test/loader/moduleName');
      expect(m.address)
        .to.be.equal(System.baseURL + 'test/loader/moduleName.js');
    })
    .then(done, done);
}); 

// Le file test/loader/moduleNameInSystem.js
System.register([], function (_export) {
  "use strict";

  var name, address;
  return {
    setters: [],
    execute: function () {
      name = _export("name", __moduleName);
      address = _export("address", __moduleAddress);
    }
  };
});
```

**Is this case correct ?**

The test is actually passing with an ES6 notation (see https://github.com/ModuleLoader/es6-module-loader/blob/master/test/system.spec.js#L328-L338) but not with the "System/Loader" notation above.

**Comment by guybedford** [comment]
How did you generate the file `moduleNameInSystem.js`? From 6to5?

`__moduleName` and `__moduleAddress` should both be there yes.

**Comment by douglasduteil** [comment]
Yep I used 6to5 with the `--modules system` option.

**Comment by guybedford** [comment]
@douglasduteil yes 6to5 doesn't generate the `__moduleName` and `__moduleAddress` variables.

I've created an issue to ensure they are defined by the register extension here - https://github.com/systemjs/systemjs/issues/340.

**Comment by douglasduteil** [comment]
@guybedford Is it normal or a PR is required ?

**Comment by guybedford** [comment]
When I do work on that PR I will post in any changes needed in 6to5. Is this something you need?

**Comment by douglasduteil** [comment]
Yep :)

**Comment by guybedford** [comment]
In the mean time I would suggest manually adding in a `__moduleName` where you need it in your custom build step? Or is this related to testing?

**Comment by douglasduteil** [comment]
I'm writing it by hand for now because I'm not heavily depend on it. Can you link the working progress 6to5 PR for that so I can keep track of it ?

**Comment by guybedford** [comment]
Rather follow this at https://github.com/systemjs/systemjs/issues/340, which needs to come before a 6to5 PR for this work.
