### ISSUE TITLE
Cache busting querystring appended twice when using json plugin

### ISSUE THREAD

**Issue by AlexKey** [ModuleLoader/es6-module-loader#301]
Hi,

I'm finding that when using the systemjs json plugin along with the cache busting technique, that it will result in the cache busting querystring being appended twice.

It's a bit of an edge case I suppose, but one I'm running into.

I've put together a jsfiddle example, it's got a few odd bits to load from rawgit etc, but is similar to my use case:

http://jsfiddle.net/alexkey/suuj8t5r/5/

Thanks for the help

**Comment by AlexKey** [comment]
I'm guessing this is perhaps related to:
"Strange URL clipping with plugins + paths" #235
and therefore "Separate '.js' extension adding from paths implementation" #169 ?

So maybe it'll be automagically fixed as part of those?

**Comment by AlexKey** [comment]
Using some thing similar to below, will kinda work, it'll stop the double "v=" however 456 will be cropped probably due to the tickets mentioned above.

```javascript
    var systemLocate = System.locate;
    System.locate = function (load) {
        return Promise.resolve(systemLocate.call(this, load)).then(function (address) {
            if (address.indexOf('v=') > -1) {
                return address;
            }
            return address + "?v=123456;
        });
    }
```

**Comment by guybedford** [comment]
Thanks for posting - better to note this at the issue https://github.com/systemjs/systemjs/issues/172, where it may benefit others. Closing here for now.
