### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#306]
There's something odd going on here - https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/50492114#L484.

I have no idea why it's taking the args from the `npm run test:browser-traceur` command and then looking for a file at `node_modules/test:browser-traceur/package.json`. It seems this is an npm issue, but I'm not sure where that path is being input.

**Comment by douglasduteil** [comment]
Yo

**Comment by douglasduteil** [comment]
It's because the npm version is too old ...

**Comment by douglasduteil** [comment]
https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/50492114#L95

**npm scripts**  are available for **npm@^2**

**Comment by guybedford** [comment]
Amazing, that fixed it. Thanks.
