### ISSUE TITLE
disable 6to5 jsx transformer

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#309]
For ES6 Module Loader, we don't want JSX transpiled as ES6, as there is a very specific line being made between the formats. 6to5 can be used to transpile JSX fine, but then it should act in translate, not as a compiler. So the default should be for JSX to be disabled.

**Comment by matthewp** [comment]
:+1: agreed.

**Comment by guybedford** [comment]
Thanks. Added in https://github.com/ModuleLoader/es6-module-loader/commit/48acf7e82f7049b8a577982888ff8913b1f367c2.
