### ISSUE TITLE
System.import with a default export

### ISSUE THREAD

**Issue by chrisbateman** [ModuleLoader/es6-module-loader#310]
When you import a module with only a default export, is it expected that you'd have to call `.default` to access it?
```
System.import('module').then(function(m) {
    m.default;
});
```

I ask because I noticed that when Babel compiles to AMD - if the module only has a default export, that default export gets returned directly. Only after you've added a named export to the module do you need to use `.default`.

I wasn't able to tell what the expected behavior is from the current spec.

**Comment by guybedford** [comment]
When importing AMD or CommonJS, SystemJS adds a helper to ensure you don't have to do this, but strictly you should. That code is here - https://github.com/systemjs/systemjs/blob/master/lib/extension-core.js#L25.

The other behaviours are all interop solutions that allow for consistent behaviours with what users would expect.

The spec doesn't define how to load other formats, that's something that's through these interops in transpilers and loaders.

**Comment by chrisbateman** [comment]
I'm mainly curious about what the behavior of the native Loader (with a native ES6 module) will be. Is it too early to say for sure?

**Comment by guybedford** [comment]
You would need to directly access the default property.

**Comment by chrisbateman** [comment]
Alright, thanks!
