### ISSUE TITLE
Importing array of modules

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es6-module-loader#318]
I've been using an old version of the loader, and am having problems importing an array of module names using Promise.all using the latest version. My code says:
```js
Promise.all(
   imports.map(System.import)
);
```
This used to work fine but now fails with 'undefined is not a function'.

If I define each import separately, it works:
```js
Promise.all(
   [System.import(imports[0]), System.import(imports[1])]
);
```
AFAICS, the reason for this seems to be that `import` is setting `loaderObj` to `this`, and in the `map` option `this` is set to `Window` not to the loader.

How should I be doing this?

**Comment by guybedford** [comment]
`System.import` uses a `this` reference. Perhaps try `imports.map(System.import.bind(System))`.

**Comment by probins** [comment]
yeah, that does the trick. Looks like that will also be an issue in 1.0 loader, so this is probably something else that should be documented somewhere.

I take it there's been nothing further from the spec committee on this? At one time, they were sounding positive about having System.import(array) or similar.

**Comment by guybedford** [comment]
Yes it's not sounding like it will be likely. If it is something you believe to be important, do post to the spec repo. Personally I like that it encourages a single entry point.
