### ISSUE TITLE
Upgrade to traceur@0.0.86

### ISSUE THREAD

**Issue by caitp** [ModuleLoader/es6-module-loader#319]
This is blocking some ongoing work I'm doing on angular to get fix some of the issues with webkit/javascriptcore.

Thanks!

**Comment by guybedford** [comment]
Nice I see it's just been released - will do it now!

**Comment by guybedford** [comment]
Just waiting on the Travis tests to release now...

**Comment by guybedford** [comment]
Released, will be pushing out to SystemJS etc over tomorrow / Thursday.

**Comment by caitp** [comment]
Awesome, thanks!
