### ISSUE TITLE
Lazy execution of modules

### ISSUE THREAD

**Issue by Mitranim** [ModuleLoader/es6-module-loader#326]
I don't see people talking about this, but it seems like an important performance consideration: it should be possible to load modules right away, but delay their actual execution until they're needed by the currently running code (e.g. view controller). This is how the Angular 1.x module system works. It this supported in ES6 modules?

**Comment by guybedford** [comment]
Yes this is how ES6 modules work. For implementation reasons, loading AMD or CommonJS will always execute upfront.

**Comment by Mitranim** [comment]
Right. So even if you conditionally load code via `System.import`, the current implementations of ES6 modules still don't allow you to defer module execution?

**Comment by guybedford** [comment]
Bundling approaches will define modules without executing them until they are imported.

There will be a function to load a module without executing but there isn't an implementation for that in the current release.

**Comment by Mitranim** [comment]
Alright, good to know, thanks for explaining!
