### ISSUE TITLE
"Fetch is not implemented" when attempting to load module from within worker.

### ISSUE THREAD

**Issue by dkushner** [ModuleLoader/es6-module-loader#330]
The worker code that bootstraps the es6 module.

```javascript
importScripts('jspm_packages/es6-module-loader.js', 
              'jspm_packages/traceur-runtime.js',
              'jspm_packages/system.js', 
              'config.js');

System.baseURL = './';
System.import('arbeit/worker').then(function(w) {
  w.run();
}).catch(function(err) { console.error(err.stack); });
```

Not quite sure why this is popping up in this context. The source of the issue is pretty obvious in that its  coming from [here](https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L1060) though I'm not really clear on why this should be causing an issue only in the context of a web worker? I do roughly the same thing from my main page and don't have an issue.

If its not already obvious, I'm very new to the wonderful world of transpiling and ES6, but this is really the only hang-up I've had so far.

**Comment by guybedford** [comment]
You need to include `traceur-runtime` before the module loader as it will replace the `System` global with its own version of `System`.

**Comment by dkushner** [comment]
Brilliant! Thanks so much for the assist and for maintaining such an excellent project (project_s_, I guess since I'm loving systemjs-builder as well).

**Comment by guybedford** [comment]
Sure, you're welcome!
