### ISSUE TITLE
Re-enable System.define test

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#333]
My apologies @matthewp, but somewhere in the last work, unrelated changes have caused this to stop working.

It is an unstable feature that hasn't been designed into the pipeline very well. I'm happy to take fixes through PRs, but don't have the time personally to debug this right now for this release.

Note that this feature will be better supported in the upcoming loader changes.

**Comment by matthewp** [comment]
Ok, I'll fix this the next time I pull down es6ml (probably in a couple of weeks or so).

**Comment by guybedford** [comment]
Sure thanks for understanding.

**Comment by matthewp** [comment]
So is the only way to run this test now in Node?

**Comment by matthewp** [comment]
I'm a little confused, the tests are duplicated, one written in mocha for Node and the old custom test runner for the browser.  Why?  Also, the browser version of this test passes. So it's only Node for some reason.

**Comment by guybedford** [comment]
Ok sure - if it's just not running in Node then we can just add a skip for the test in Node if you're happy with that.

The manual tests there are the old tests which are being phased out but still in use right now.

**Comment by matthewp** [comment]
How do we run the mocha tests in the browser?

**Comment by matthewp** [comment]
@guybedford can we run the mocha tests in the browser?

**Comment by guybedford** [comment]
Yes, with `karma --start`. See https://github.com/ModuleLoader/es6-module-loader#testing.

**Comment by matthewp** [comment]
Is there not a way to open an html page to see a test? Karma seems great for automation but not for debugging.

**Comment by matthewp** [comment]
Can you reopen this, I was mistaken before, it's not working. Looking into why now.  I'm guessing this is the breaking commit: https://github.com/ModuleLoader/es6-module-loader/commit/c309e1126cd9cc5183e41a5c3109250b1039d48e

**Comment by matthewp** [comment]
I have a fix for the issue, but it doesn't fix the test for some reason.  Will submit a PR when I get that passing again.
