### ISSUE TITLE
Development and production loader

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#334]
For the rewrite it may be worth supporting System.register as a native module format. This way we can provide two builds of the loader - a development and production one, without duplicating any pipeline code. It also means the production loader will be the smallest possible footprint, not including code like transpiler hooks.

**Comment by matthewp** [comment]
Is System.register a specced format? I don't think es6ml should contain code that is applicable only to SystemJS.

**Comment by guybedford** [comment]
It's becoming effectively like one as it gains wider support. It closes the
loop on the loader and is necessary for production so I do think the
benefits can outweigh here.

**Comment by matthewp** [comment]
So why not throw the "spec" into a repo like https://github.com/amdjs/amdjs-api and get your traceur/babel cohorts to sign off on it?  One of the main reasons we haven't used it is because of the uncertainty that it won't be modified.

**Comment by guybedford** [comment]
That's a great point, that will most likely happen, it's just a matter of
time.

**Comment by guybedford** [comment]
Created https://github.com/ModuleLoader/es6-module-loader/issues/336.

**Comment by pkozlowski-opensource** [comment]
@guybedford I couldn't vote enough on this one. I would love more people using ES2015 module sysntax and System.import loader syntax as this is what we are going to have in browsers in the future. But I keep hearing this argument that current polyfills are "too big". Having a minimal loader that understands System.register would be a massive win.

If there are any items you need helping hands with, I would be happy to contribute.

**Comment by probins** [comment]
I think what is included in a build should be as flexible as possible. I agree that it would be good to support `register` without transpiler hooks, and also to have a version without any hooks. However, v8 has started work on implementing import/export to the current spec, so at some point soon we should be able to use Chrome/ium or io.js without the need for any transpiling. It's not clear at the moment whether this will continue behind a flag. If so, browser use can't really be considered 'production'. But those who want to develop using this won't need transpilation. So I'm not sure the production/development split is all that useful. I think it would be better to differentiate environments that support loading/`System.import` (no need for polyfill; probably quite a way off), those that support parsing of import/export (need for polyfill, but not for transpiling; some envs probably quite soon), and those that do neither (need for polyfill and either `register` or transpile functionality).

**Comment by pkozlowski-opensource** [comment]
@probins I think the real question here is time-frame. It is great that V8 (and probably other browsers!) are moving with the spec impl but the question is - when all the browsers in the wild will behave.

I can really see the current size of a loader as being a factor that prevents people from switching to ES6 module syntax + System.import poly.

If we could say that:
* people could write ES6 module syntax today
* people could use System.import syntax in a browser today
and all this with a "minimal" loader / polyfil I think that it would speed up adoption ration of ES6 modules and would get us out of the current messy situation quicker.

**Comment by guybedford** [comment]
It will be a long time before we can rely usefully on the implementations in browsers - having ES6 module support is separate to having `System.import` support. And the `System.import` spec needs to be finished first before implementations can start.

Supporting this minimal loader work and getting the new versions of the loaders out is my top priority at the moment. The goal is to get these features out in a 1.0 of the Module Loader and SystemJS. The 1.0 branch here contains the most recent spec version of the loader (https://github.com/ModuleLoader/es6-module-loader/tree/1.0).

**Comment by pkozlowski-opensource** [comment]
@guybedford thrilled to hear this! I think that a minimal, production-ready loader would be awesome. I was toying with https://github.com/caridy/es6-micro-loader but yeh, something with "meant to be used in prod and is small" stamp would be awesome.

**Comment by pkozlowski-opensource** [comment]
BTW, it looks like TypeScript guys are considering an option to have System.register output. As such we would have several major transpiles capable of producing the same output for ES6 modules.

**Comment by guybedford** [comment]
I heard that might be a possibility - sounds really amazing! TypeScript is an ideal language for a module loader actually, since it naturally supports dynamic linking. Lots of users have been using it which has been great to see, so it would be really nice to make those workflows easier.

If there are any questions on the format I'm always happy to help. https://github.com/ModuleLoader/es6-module-loader/issues/336 is not a major priority for me right now, but if it would help adoption I can always get that going too.

**Comment by guybedford** [comment]
Work on this is being tracked at https://github.com/ModuleLoader/es6-module-loader/pull/341.

**Comment by probins** [comment]
> having ES6 module support is separate to having System.import support. And the System.import spec needs to be finished first before implementations can start.

agreed. But my point is that this isn't really prod vs dev, but what envs support what. However, having said that, it looks like the code is split out into separate files, so it should be flexible enough to meet all purposes.

**Comment by matthewp** [comment]
So is es6-module-loader no longer going to be a polyfill, if it includes non-spec code?  I understand the practical benefits of doing this but how many projects are using bare es6ml and not a derivative?

**Comment by guybedford** [comment]
@matthewp I tend to agree that taking away the polyfill property is too drastic.

Instead, there will be a minimal build here, and then another minimal build in SystemJS that just has the register extension. That will then get us down to a highly streamlined production loader.

The builds for 1.0 are implemented in https://github.com/ModuleLoader/es6-module-loader/tree/1.0/dist.

@matthewp also about the 1.0 branch - it will go through a succession of betas (side-by-side with the current 0 release) only reaching a stable 1.0 when the spec shows signs of stability (perhaps in the next few months, perhaps not). Even then as spec changes continue, we can revise major releases.

The betas will allow other projects to build on and play with the new spec though, which is important to put into the hands of users.

**Comment by matthewp** [comment]
@guybedford That sounds like a good plan, thanks for listening.

You now have the burden of being popular so the 0.* line is going to hang around for quite a long time, I think.

**Comment by guybedford** [comment]
Yeah that is somewhat unfortunate.

It may even be necessary to make the new SystemJS changes on both branches for a while I guess.

**Comment by guybedford** [comment]
This work is now on the master branch:

* The Promise polyfill is no longer bundled in.
* The primary build remains exactly as before.
* The production build is the new minimal build.

**Comment by probins** [comment]
> This work is now on the master branch

did you mean 'master' here? I see loader and loader.dev in 1.0 branch dist, but not in master

**Comment by guybedford** [comment]
@probins I haven't done the build on master yet, but it's there in the gruntfile and code.

**Comment by pkozlowski-opensource** [comment]
@guybedford sorry for commenting on the closed issue but I'm trying to track work on the minimal loader with System.register support. I was under the impression that it was cooking as part of the PR #341 and it was merged as  5b5532a. But now I can't see this commit / associated files in any branches (master nor 1.0).

Would you mind sharing what has happened with this work? Were some problems discovered that resulted in it being removed? 

More generally, what is the status of creating a build that would contain minimal prod loader (so no references to transpilers) + System.register support? 

Is there anything I could help with to progress on this topic?

**Comment by guybedford** [comment]
@pkozlowski-opensource the branch can be found at https://github.com/ModuleLoader/es6-module-loader/tree/0.17. It goes along with https://github.com/systemjs/systemjs/tree/0.17. Both are passing tests, but there are a few things that need to align for the release. I'm hoping to get it out very soon though.

The SystemJS version doesn't have a build, so needs a `npm install && make`. Feel free to try it out and let me know what you think. The minimal loader build of SystemJS is the "minimal production loader", but currently contains SystemJS config as well. Were you looking for the minimal module loader build only?

**Comment by pkozlowski-opensource** [comment]
@guybedford OK, will build SystemJS and see what in there. I'm still slightly confused since 5b5532a0fadfc73b96fa13cbc0ffa46879e34251 had the `src/register.js` file so I was assuming that I will only need to deal with es6-module-loader project.

At the end of a day I'm looking for a minimal build that only supports `System.register` format and doesn't try to compile anything on a client.

**Comment by guybedford** [comment]
That was the initial plan, but `System.register` is heavily tied to features like bundles and an encapsulation of dynamic linking, which as @matthewp said were a bit much to include as well in the end. Can always reconsider though.

There isn't currently a build with just the register extension, but it would be easy to do one from the SystemJS makefile. The size should be pretty good now.

Just let me know if you have any further questions at all.

**Comment by pkozlowski-opensource** [comment]
@guybedford thnx for coming back to me. Let me build SystemJS + es6-module-loader from 0.17 and see how it goes. I can always package those on my end but I wonder if this is not common-enough use-case to have a dedicated build.

**Comment by guybedford** [comment]
@pkozlowski-opensource would you really want just the System register extension without features like map configuration and plugins? Note I've committed the build in https://github.com/systemjs/systemjs/tree/0.17/dist now (it is now a combined ESML + SystemJS build, and the size is looking about half!)

**Comment by pkozlowski-opensource** [comment]
@guybedford thnx for adding dist to 0.17 - I actually built this myself, but having this available makes my live easier. Thnx!

Now, checking the size it is indeed much better! But I was slightly surprised to see that it is bigger as compared to es-module-loader + register plugin from SystemJS. So this combo in 0.17 dist is definitively usable for me right now but I would be great to see if we can make it even smaller. 

Essentially my workflow is (for prod) to have everything in the System.register format so I don't need to mix & match various module formats in one app. So I guess I don't need "plugins" for my use-case. Not sure what is exactly in the "map configuration" part at this point to say if I need it or not :-) Sorry, still digging into the details...

**Comment by guybedford** [comment]
Sure! The System-prod build is exactly for System register only via script
injection and comes in at 8KB minified and gzipped.

We can get it smaller removing features like plugins, but it is useful to
reduce API complexity not having too many surprises, and the size
difference after that won't be that big anyway (maybe 6 or 7 at a stretch
aggressively removing features that are useful).

**Comment by guybedford** [comment]
@pkozlowski-opensource I've added a "register-only" build in https://github.com/systemjs/systemjs/tree/0.17/dist which cuts down from 8.5KB to 6.5KB for everything gzipped. Still not entirely sure about this build, but perhaps the idea of an absolute minimum build can be useful.

**Comment by pkozlowski-opensource** [comment]
@guybedford thnx for the update and the awesome news! I'm testing those builds now, but I'm not sure what is the compatible systemjs-builder version that can produce `System.registerDynamic` output. 0.10.4 seem to produce `System.register` calls with 4 arguments while 0.17 of SystemJS seems to expect `System.registerDynamic` calls.

I'm bumping into it since I'm bundling ES6 module with one CJS module....

**Comment by guybedford** [comment]
@pkozlowski-opensource I'm working on the SystemJS builder branch at the moment. For now, you can manually rename to `System.registerDynamic` where it is the CommonJS `System.register`. Otherwise I should have the branch ready tomorrow.

**Comment by guybedford** [comment]
@pkozlowski-opensource https://github.com/systemjs/builder/pull/138 is now in to match the changes! Sorry didn't mean to throw you in at the deep end here... it may just be worth waiting for the release.

**Comment by pkozlowski-opensource** [comment]
@guybedford no worries, I'm used to dealing with the bleeding - edge stuff :-) I'm unblocked now, I can test things etc. so this is the most important! For a bit of the context, we are experimenting with various formats / loader setups for Angular 2 so this is why I'm looking into this topic. I want to make sure that people can use this stuff in real-life, production apps today, so this is why I'm focusing on size, ease of us etc.

And hey, thnx so much for all the work on those projects (it looks like the future of ES6 modules loading is on your shoulders now! I will try to help as much as possible, though), all the help and reactivity. This is   true open source collaboration!

**Comment by guybedford** [comment]
@pkozlowski-opensource sure, thanks glad to help where I can! Just let me know if there's anything I can do from this side. For I'm now just focusing on getting this release cycle through, feedback is always welcome.
