### ISSUE TITLE
__dirname of loaded module points to es6-module-load/dist/ dir

### ISSUE THREAD

**Issue by nicroto** [ModuleLoader/es6-module-loader#335]
Hi,

Awesome project!

I am trying to load an ES6 module, which loads an html template located in the same dir as the module.

File structure:
```
project
    node_modules
    src
        utils.js
        template.html
    test
        utils-test.js
```

```javascript
// utils.js
...
let classPreivew = fs.readFileSync( path.resolve( __dirname, "template.html" ), "utf-8" );
...
```

But when I try to load `utils`, like this:

```javascript
// utils-test.js
...
var System = require('es6-module-loader').System;

System.baseUrl = path.resolve( __dirname, "..", "src" );
System.import( "../src/utils" ).then( function(u) {
	utils = u;
} );
...
```

I get the following error:

```
Potentially unhandled rejection [2] Error: ENOENT, no such file or directory '/path/to/project/node_modules/es6-module-loader/dist/template.html'
```

It seems that `__dirname` is not what it should be.

As you can see, I have tried setting the baseUrl.

**Comment by guybedford** [comment]
Try using the `__moduleAddress` global here instead? Note that this does have some bugs which is why it isn't documented, although I'd be happy to help fix them.

The actual syntax for this in ES6 will change when the spec proposal for this eventually arrives.

**Comment by nicroto** [comment]
Thanks. That's what I am using right now.

In my case, I build an extension for my app [Pagehop](https://pagehopapp.com).
Every extension is a *browserifiable* NodeJS module and they run in a headless browser, they don't run in Node. I use es6-module-loader as a dev-dependency in tests - instead of browserifying the module and then running tests through a browser, I try to test whatever I can as a regular node module.

Unfortunately, because of this problem and because of the [fragile JavaScript parsing of the brfs browserify transform](http://api.pagehopapp.com/external-dependencies/#Loading_textual_resources_through_fs-readFileSync()) (allows you to use fs.readFileSync and then replaces these usages with the actual file content while browserifying), all of my ES6 modules using fs.readFileSync should now have this non-es6 snippet on the top:

```javascript
// <Don't use ES6 on this chunk of code!!!>
var fs = require('fs');
var path = require('path');

if ( typeof( __moduleAddress ) !== "undefined" ) {
	__dirname = path.dirname( __moduleAddress.replace( "file:", "" ) );
}

var template = fs.readFileSync( path.resolve( __dirname, "template.html" ), "utf-8" );
//... list the rest of the loaded static resources
// </>
```

Do you think we can add the __dirname, the same way __moduleAddress is added when executing the module? This way I can get rid of the `if-statement`. :(

And finally, could you please share some links or shed some light on the bugs that you mentioned, so maybe I can try and *avoid capture*.

Thanks.

**Comment by guybedford** [comment]
If you write your modules as CommonJS and use SystemJS it will define the `__dirname` and `__filename` globals for you.

Any ES6 features you want to use can be precompiled to CJS with such a workflow allowing all the benefits too.

There's very little info on the new meta syntax online at the moment. Will definitely update here when it's available. It's a longer-term change though (1 year+).

**Comment by nicroto** [comment]
Thanks for the help.
