### ISSUE TITLE
Publish System.register spec

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#336]
Along with bringing System.register into this codebase, we should publish the format as its own spec document properly.

**Comment by pkozlowski-opensource** [comment]
Oh yes, please do! I would love to see more transpilers (TypeScript?) supporting this format so we can effectively decouple module system syntax (one that people use to write their modules) from the output ("transport" format) and various loaders! 

Great initiative, thank you!

**Comment by guybedford** [comment]
https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained is still as close as we've got to a spec. And since we now have all the transpiler implementations anyway, it's difficult to justify further work on this for the time input. Any help is always welcome here though.

**Comment by guybedford** [comment]
This is not currently a priority as I'm not sure what good reason there is for this.
