### ISSUE TITLE
When doesn't respect the native Promise implementation.

### ISSUE THREAD

**Issue by fd** [ModuleLoader/es6-module-loader#338]
See: cujojs/when#442

**Comment by guybedford** [comment]
When I last tested (although quite a few months ago now), When was actually still much faster than native promises, making this a good thing.

We do have builds without the promise implementation though if this is needed, see https://github.com/ModuleLoader/es6-module-loader/blob/master/dist/es6-module-loader-sans-promises.js.

**Comment by fd** [comment]
The reason I want native Promise when available is so that Chrome can help debugging them. (with their new Promise inspection panel)

Would it be possible to use when just in es6-module-loader internally.

**Comment by guybedford** [comment]
Is there a reason you can't just use the `sans-promises` build here?

**Comment by fd** [comment]
I don't like swapping out dependencies based on development/production differences.

As for the performance problems. Eventually native should always be faster than any JS polyfill. So having a slow Promise for 18 weeks (three release cycles in Chrome/FF) seems reasonable. Also browser vendors that refuse to improve their implementations should not be let off the hook that easily (looks at Safari/Mobile Safari for not having a proper release schedule).

On the other hand I do understand the desire to have everything work perfectly everywhere.

Note: 18 weeks to move from canary/nightly to stable.

**Comment by guybedford** [comment]
@fd you can use the `sans-promises` entirely for both dev and production.

**Comment by fd** [comment]
@guybedford sure that's true.
