### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by hekke** [ModuleLoader/es6-module-loader#339]
It seems that this simple example tries to eval the inline module each time an import is resolved.

http://www.hekke.dk/es6-babel-bug.tar.gz

In Chrome the console outputs:
Uncaught ReferenceError: require is not defined

I don't know if this is an issue with es6-module-loader or babel?

**Comment by guybedford** [comment]
@hekke I think the issue here is that the `<script type="module">` is being processed by both Babel and ES6 Module Loader.

To stop Babel from processing it, you can rather have Babel loaded automatically by ES6 Module Loader by setting:

```javascript
  System.paths.babel = 'node_modules/babel/browser.js';
```

**Comment by hekke** [comment]
It works!
Thank you so much!
