### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by stagas** [ModuleLoader/es6-module-loader#340]
This line causes an issue:

https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L459

as in the implementation of `linkSetFailed()` there is no check for `load` being `null`:

https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L515

I have no idea what any of these do but I discovered this error trying to export a generator function:

https://gist.github.com/stagas/d057855fff26d5a8050b

**Comment by guybedford** [comment]
I think this is due to https://github.com/babel/babel/pull/1105, which will be fixed in the upcoming release of Babel.

For now you can disable the runtime transformer in Babel as a workaround - `babelOptions: { optional: [] }`.

**Comment by stagas** [comment]
I see, thanks. Still the issue of not checking for `load` being `null` during that execution path and showing a more helpful error, remains, I think.

**Comment by guybedford** [comment]
This is due to an invalid System.register output, so creates a slightly obscure error I understand. But it's very much an edge case in the error system.
