### ISSUE TITLE
Errors using es6-module-loader from iojs on Windows

### ISSUE THREAD

**Issue by chucksellick** [ModuleLoader/es6-module-loader#342]
Have tried all of following:
a) installing babel locally to module
b) installing traceur locally to module
c) installing babel globally
d) installing traceur globally

With any of the above, es6-module-loader still reports an error when I try and import a file which using ES6 syntax. The same same file works fine transpiling for Either it can't find traceur (apparently never attempts to use babel) or I see the following error from Traceur:

Error loading "filename" at file: C:/Path/to/project/filename.js
Error loading "traceur" at C:/Path/to/project/node_modules/traceur/bin/traceur.js
Only file URLs of the form file: allowed running in Node.

It's that last bit "Only file URLs of the form file: allowed running in Node." ,,, not sure where this error derives from.

But the main issue is that I can't seem to use Babel here at all. I just get "ENOENT: no such file or directory, open 'C:\Path\to\project\babel.js'" with either global or local install of Babel (after setting System.transpiler = "babel").

**Comment by guybedford** [comment]
Thanks, yes this is a bug, we should be adding `file:` to the beginning of the path at https://github.com/ModuleLoader/es6-module-loader/blob/master/lib/index-traceur.js#L5 and https://github.com/ModuleLoader/es6-module-loader/blob/master/lib/index-babel.js#L6.

Note that the workaround is to do `System.paths['babel'] = 'file:' + require.resolve('babel-core/browser.js')`.

**Comment by guybedford** [comment]
(assuming you install `npm install babel-core` for a quicker install as a transpiler)
