### ISSUE TITLE
Allow file URLs of the form http: in Node.

### ISSUE THREAD

**Issue by laurentdesmet** [ModuleLoader/es6-module-loader#344]
Is there a specific reason why only `file:` URLs are allowed in Node? I'm using the systemjs-builder that depends on this project to bundle multiple ES6-modules and it would be handy to fetch modules from some online-endpoint using `http:`.

**Comment by guybedford** [comment]
I think the main reason is that it would be highly inefficient to do build operations that block on HTTP requests.

If you really want this functionality you can add the functionality to `builder.loader.fetch` yourself.
