### ISSUE TITLE
Reflect.Module specified descriptors and mutators

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#345]
The pattern for `Reflect.Module` is shown in https://gist.github.com/dherman/fbf3077a2781df74b6d8.

This forms the dynamic instantiation interface for users, so should be implemented as part of the public API.

**Comment by probins** [comment]
looks like the spec is still incomplete here: missing CreateModuleMutator() for example.

I'm thinking this will have the same limitations as `<module>` in the polyfill environment: can only support es6 `import` so has a limited usability.

**Comment by guybedford** [comment]
I don't think it should be too hard to fill the gaps. This would be used as the interface for CommonJS modules as well.

**Comment by probins** [comment]
are you planning on putting this in a separate file? At the moment, the current function is in `loader.js` but it doesn't really have anything to do with Loader; aiui it doesn't 'load' anything.

**Comment by guybedford** [comment]
It could certainly be its own file.

**Comment by guybedford** [comment]
This can track with the 1.0 spec work.
