### ISSUE TITLE
no module name in exception call stack for modules transpiled with traceur

### ISSUE THREAD

**Issue by metamatt** [ModuleLoader/es6-module-loader#355]
I just started learning systemjs. Please excuse me if I'm doing something drastically wrong on my end.

I whipped up a simple ES6 module and, because I'm concerned about debuggability of transpiled code, immediately decided to see what the error messages and call stacks look like.

I tried throwing an Error from the toplevel of the ES6 module with just `throw new Error('testError');`:

```
es6-module-loader.src.js:140 Potentially unhandled rejection [2] Error: testError
    at System.register.execute (eval at __eval (http://localhost:1080/s/pkg/es6-module-loader.js:7:12622), <anonymous>:21:13)
    at t (http://localhost:1080/s/pkg/es6-module-loader.js:7:19790)
    at v (http://localhost:1080/s/pkg/es6-module-loader.js:7:20172)
    at u (http://localhost:1080/s/pkg/es6-module-loader.js:7:19848)
    at s (http://localhost:1080/s/pkg/es6-module-loader.js:7:19729)
    at http://localhost:1080/s/pkg/es6-module-loader.js:7:22056
    at O (http://localhost:1080/s/pkg/es6-module-loader.js:7:7439)
    at K (http://localhost:1080/s/pkg/es6-module-loader.js:7:7071)
    at y.7.y.when (http://localhost:1080/s/pkg/es6-module-loader.js:7:10745)
    at v.7.v.run (http://localhost:1080/s/pkg/es6-module-loader.js:7:9781)
```

and throwing the same error using Angular and $timeout:

```
Error: testError
    at eval (eval at __eval (http://localhost:1080/s/pkg/es6-module-loader.js:7:12622), <anonymous>:21:17)
    at http://localhost:1080/s/pkg/github/angular/bower-angular@1.4.0-beta.6/angular.js:17105:31
    at completeOutstandingRequest (http://localhost:1080/s/pkg/github/angular/bower-angular@1.4.0-beta.6/angular.js:5073:10)
    at http://localhost:1080/s/pkg/github/angular/bower-angular@1.4.0-beta.6/angular.js:5335:7
```

The way I understand using `eval` to transpile code, this should work if you pass the browser a nice label for the source string that you `eval`, by sticking a `//# sourceURL=` annotation in there. I went looking for that in the es6-module-loader code and found it in the Babel transpile path, but not in the (otherwise similar) Traceur transpile path:

```
    // add "!eval" to end of Traceur sourceURL
    // I believe this does something?
    source += '!eval';
```

```
    // add "!eval" to end of Babel sourceURL
    // I believe this does something?
    return source + '\n//# sourceURL=' + load.address + '!eval';
```

I tried configuring sytemjs to transpile with babel instead of traceur, and I get much nicer call stacks:

```
Potentially unhandled rejection [2] Error: testError
    at System.register.execute (http://localhost:1080/s/loader/loader.js!eval:21:16)
    at t (http://localhost:1080/s/pkg/es6-module-loader.js:7:19790)
    at v (http://localhost:1080/s/pkg/es6-module-loader.js:7:20172)
    at u (http://localhost:1080/s/pkg/es6-module-loader.js:7:19848)
    at s (http://localhost:1080/s/pkg/es6-module-loader.js:7:19729)
    at http://localhost:1080/s/pkg/es6-module-loader.js:7:22056
    at O (http://localhost:1080/s/pkg/es6-module-loader.js:7:7439)
    at K (http://localhost:1080/s/pkg/es6-module-loader.js:7:7071)
    at y.7.y.when (http://localhost:1080/s/pkg/es6-module-loader.js:7:10745)
    at v.7.v.run (http://localhost:1080/s/pkg/es6-module-loader.js:7:9781)
```

But much longer load time in browser. And traceur is the default transpiler in systemjs.

I presume adding the `# sourceURL` annotation on the traceur path would help.

**Comment by metamatt** [comment]
I tried adding the same sourceURL annotation on the traceur path (I just hand-edited it into the minified .js because that was easier to do than figure out how to get system.js to load the unminified es6-module-loader.src.js.

Works great, i.e. I get the right module name in the backtrace, same as with babel.

Note that the line number isn't quite right, because the backtrace is for the transpiled code, not the source code. (Maybe there's a goal of using source maps so that the browser can map back to the original source location?) But that's not a huge deal, and it's already true for babel in the example above (that is, my `throw new Error` call is actually at line 13 of `loader.js`, but after transpile `loader.js` has turned into `loader.js!eval` which has a few lines of prologue, so the `throw new Error` has moved down to line 21).

But now I see the point of the "!eval" trick, and it works out pretty nicely -- both the original ES6 source that I wrote and the transpiled ES5 source that the browser executes are visible in the Sources tab of Chrome devtools.

**Comment by metamatt** [comment]
One more factor here: digging through the transpiled code in the devtools Sources viewer, I see there's already a `# sourceMappingURL` annotation there but it's not at the top level.

The module as I defined it is wrapped in 2 layers of `function(){}`, the inner one is the `System.register` callback for dependency resolution, the outer one is an anonymous function of no arguments which I assume is just there to avoid scope pollution. And the `//# sourceMappingURL` annotation is on the inner function. But I believe the `//#` annotations are magic things interpreted by `eval` only at the end of the `eval`'d string, not at function granularity inside the `eval`'d string.

That's all to say that something tried to generate a source map and use it, but then something else came along afterwards and wrapped up this nicely labelled payload in another layer of function/closure that hides the annotation. I think.

The module.js!eval payload after transpilation looks something like

```
(function() { var __moduleName = "s/loader/socket"; var __moduleAddress = "http://localhost:1080/s/loader/socket.js";System.register([], function (_export) {
  var socket;
  return {
    setters: [],
    execute: function () {
      'use strict';

      // XXX should load socket.io with systemjs instead
      /* global io */

      socket = io.connect();

      _export('default', socket);
    }
  };
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MTA4MC9zL2xvYWRlci9zb2NrZXQuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtNQUtJLE1BQU07Ozs7QUFMVixrQkFBWSxDQUFDOzs7OztBQUtULFlBQU0sR0FBRyxFQUFFLENBQUMsT0FBTyxFQUFFOzt5QkFFVixNQUFNIiwiZmlsZSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTA4MC9zL2xvYWRlci9zb2NrZXQuanMiLCJzb3VyY2VzQ29udGVudCI6WyIndXNlIHN0cmljdCc7XG5cbi8vIFhYWCBzaG91bGQgbG9hZCBzb2NrZXQuaW8gd2l0aCBzeXN0ZW1qcyBpbnN0ZWFkXG4vKiBnbG9iYWwgaW8gKi9cblxudmFyIHNvY2tldCA9IGlvLmNvbm5lY3QoKTtcblxuZXhwb3J0IGRlZmF1bHQgc29ja2V0O1xuIl19
 }).call(__global);
```

So the source map is present but I don't think it's getting used. (This is true of both the traceur and babel paths.)

**Comment by guybedford** [comment]
Thanks so much for posting this - I did actually fix this in the 0.17 upcoming release branch, but hadn't backported to this branch. I've added the fix in https://github.com/ModuleLoader/es6-module-loader/commit/20ced0ce1faf3da29fab36590f87a8b0e08904dd with a release to follow.

**Comment by metamatt** [comment]
Sweet, thanks.

BTW, is the actual intent that the source map get used (via the sourceMappingURL annotation) instead of the sourceURL annotation? That would probably work even better; it looks like both babel and traceur are going to the trouble of generating a source map which I assume is correct.

2 things I noticed (but I haven't tried building from source and changing any of this) are that

(1) the function as transpiled by babel/traceur (which has the sourceMappingURL annotation) is then wrapped by another layer of function which I believe hides that annotation.

(2) an earlier version of this code (up until 8ee0ba4b5ec3ca218efc66ac670f9fad8a9f26c3) had an explicit call to `compiler.getSourceMap();` on the traceur path (but not the babel path). The value of that was never used. And I don't know if babel has a similar API.

So both letting the transpiler annotate the function, or transpiling without creating the annotation but then asking for the source map afterwards and appending it at the very end, seem like they could work but aren't quite wired up.

**Comment by guybedford** [comment]
Even with the function wrappings, I believe the source maps still get picked up fine. You should get line-by-line debugging of ES6 for both Traceur and Babel and we run manual tests of this regularly - the particular Traceur issue just slipped through the cracks as they changed their inlining behaviour. The inline sourceMaps option we pass to both Traceur and Babel makes them generate and inline the sourceMappingURL into the source file itself, containing a data-uri encoded source map which the browser can fully interpret. If you're not getting this behavior then please do let me know though.

**Comment by metamatt** [comment]
OK, the source maps are working, at least mostly. I'm confused by the overlap between source map (exposed via sourceMappingURL annotation) and the sourceURL annotation. Seems to me if the source map is working, we wouldn't actually need the sourceURL annotation, because the source map already had the code itself inline.

But things seem to work better with both sourceMappingURL and sourceURL supplied.

I threw this code at the top level of a ES6 module:
```
console.debug(new Error('toplevel sync stack').stack);
setTimeout(function testStack() {
   console.debug(new Error('async stack').stack);
});


setTimeout(function testThrow() {
   throw new Error('async throw');
});
throw new Error('toplevel sync throw');
```

and the output is

```
loader.js:15 Error: toplevel sync stack
    at System.register.execute (loader.js:15)
    at t (es6-module-loader.src.js:2118)
    at v (es6-module-loader.src.js:2165)
    at u (es6-module-loader.src.js:2128)
    at s (es6-module-loader.src.js:2103)
    at es6-module-loader.src.js:2293
    at O (es6-module-loader.src.js:1183)
    at K (es6-module-loader.src.js:1142)
    at y.7.y.when (es6-module-loader.src.js:930)
    at v.7.v.run (es6-module-loader.src.js:821)
loader.js:17 Error: async stack
    at testStack (loader.js:17)
loader.js:23 Uncaught Error: async throwloader.js:23 testThrow
es6-module-loader.src.js:140 Potentially unhandled rejection [2] Error: toplevel sync throw
    at System.register.execute (http://localhost:1080/s/loader/loader.js!eval:28:13)
    at t (http://localhost:1080/s/pkg/es6-module-loader.js:7:19816)
    at v (http://localhost:1080/s/pkg/es6-module-loader.js:7:20198)
    at u (http://localhost:1080/s/pkg/es6-module-loader.js:7:19874)
    at s (http://localhost:1080/s/pkg/es6-module-loader.js:7:19755)
    at http://localhost:1080/s/pkg/es6-module-loader.js:7:22082
    at O (http://localhost:1080/s/pkg/es6-module-loader.js:7:7453)
    at K (http://localhost:1080/s/pkg/es6-module-loader.js:7:7085)
    at y.7.y.when (http://localhost:1080/s/pkg/es6-module-loader.js:7:10759)
    at v.7.v.run (http://localhost:1080/s/pkg/es6-module-loader.js:7:9795)
```

Note that for the "toplevel sync throw" case, the call stack is in `loader.js!eval`, not `loader.js`. That is, it's visibly in the transpiled code, with line numbers different from the original ES6 source. Which to me indicates this case is not using the source map.

The other cases show the exception in `loader.js` with a lower line number, which is correct according to the original (not transpiled) source, which to me indicates these cases are using the source map.

But for additional weirdness, look at the 2 call stacks for es6-module-loader.js itself. In the "toplevel sync throw" case, all the frames inside es6-module-loader are for the minified code (function name, filename, line:column offset are all for the minified .js file). In the "toplevel sync stack" case, for the frames inside es6-module-loader, the function names are still for the minified code, but the filename and line:column offset are for the original .src.js file. Which seems to mean the browser is using a source map somewhat incompletely for the "sync stack" case and not at all for the "sync throw" case?

This is all new and interesting to me; maybe it makes more sense to someone else? Thanks for bearing with my curiosity.

**Comment by guybedford** [comment]
Thanks for looking into it. Yes this is a known issue (https://github.com/ModuleLoader/es6-module-loader/issues/293#issuecomment-71807109) - when the browser executes code that fails in the immediate sync thread, it hasn't yet had time to load the source map, or source URL and doesn't include any of this debugging info. You can create a breakpoint which will work. Perhaps the breaking on error option is supported though.

So you only get the nice debugging output for errors that are out of the synchronous initial execution of code, which isn't ideal I know, but it's in the browser handling of source maps and not anything we're doing.

The reason for having both sourceURL and sourceMappingURL is that line-by-line debugging stops working when we remove the sourceURL. Again just jumping through the hoops as best as possible to make browsers behave.

**Comment by metamatt** [comment]
Got it. Thanks for the explanation.
