### ISSUE TITLE
Error in System Import of React in Node Application

### ISSUE THREAD

**Issue by dfbaskin** [ModuleLoader/es6-module-loader#357]
I was working with React server-side rendering in a NodeJS application and was having problems importing the React module.  Maybe I'm doing something wrong, though.  Here's a very simple example that shows the error that is being generated.

I have a single import file:

```javascript
import React from 'react';
export default ['one', 'two', 'three'];
```

Then I have a single script for Node to execute:

```javascript
var System = require('es6-module-loader').System;
System.transpiler = 'babel';
System.paths.react = 'file:' + require.resolve('react/lib/react.js');

System
    .import('simple-import')
    .then(function(x) {
        console.log("Imported:", x);
    })
    .catch(function (error) {
        console.log("Error:", error);
    });
```

And I get this error:

```
Error: { [Error: Error loading "react" at file:.../node_modules/react/lib/react.js
Error loading "react" from "simple-import" at file:.../simple-import.js
file:.../node_modules/react/lib/react.js:
We don't know what to do with this node type. We were previously a Statement but we can't fit in here?]
_babel: true }
```

This error appears to be saying that Babel is having a problem compiling the React file, but this file has no errors when run through Babel directly from the command line.

Any idea as to what is going on here?

**Comment by guybedford** [comment]
This project on its own doesn't come with support for loading CommonJS and global files. Try using SystemJS instead.

**Comment by dfbaskin** [comment]
Ok, thanks.  I guess I was confused as to the relationship between es6-module-loader and systemjs.  And I ended up getting it to work using jspm.
