### ISSUE TITLE
[1.0] Would suggest changing xhr to fetch()

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es6-module-loader#358]
The Fetch API is specifically mentioned in the spec, is now supported in stable Chrome, and is in Firefox 39. It's a simpler interface, so would reduce the size of the loader a bit for browsers that support it. There's a polyfill for other browsers https://github.com/github/fetch

**Comment by guybedford** [comment]
While this would be nice, the fetch implementation is far bigger than the XHR implementation here, so I don't think the benefits outweigh the costs. The XHR implementation is not a major contributor to the code footprint either.
