### ISSUE TITLE
import { module } without export default

### ISSUE THREAD

**Issue by markbrown4** [ModuleLoader/es6-module-loader#359]
I'm trying to import a specific module using the import {} syntax but it's not working as expected.

```js
import RedditApi from './reddit-api.coffee!'
console.log(RedditApi);
// Object { RedditApi=RedditApi }

import { RedditApi } from './reddit-api.coffee!'
console.log(RedditApi);
// undefined
```
Shouldn't import { RedditApi } pull the RedditApi object out of the module?

https://github.com/markbrown4/jspm-intro/blob/master/lib/main.js
https://github.com/markbrown4/jspm-intro/blob/master/lib/reddit-api.coffee

**Comment by guybedford** [comment]
Importing CommonJS from ES6 always assigns the CommonJS module to the default ES6 export. There is an issue tracking this support in SystemJS as a convenience feature at https://github.com/systemjs/systemjs/issues/334. This will be supported in the next major SystemJS release.
