### ISSUE TITLE
webworker ios7

### ISSUE THREAD

**Issue by MajorBreakfast** [ModuleLoader/es6-module-loader#361]
- [ ] Same problem (WorkerGlobalScope is not defined) and [solution](https://github.com/ModuleLoader/es6-module-loader/blob/c309e1126cd9cc5183e41a5c3109250b1039d48e/src/polyfill-wrapper-end.js#L15-L16) as in https://github.com/systemjs/systemjs/issues/409
- [ ] `console.assert` causes error because `console` isn't defined on iOS7 web workers. Something like `var console = __global.console || {}` is needed. [loader.js#L107-L108](https://github.com/ModuleLoader/es6-module-loader/blob/8c6a1db15f6924f53a1d61c4c102237a1fe7d8a8/src/loader.js#L107-L108) will add the method then. (The if is not needed, I think)

**Comment by MajorBreakfast** [comment]
https://github.com/ModuleLoader/es6-module-loader/blob/c309e1126cd9cc5183e41a5c3109250b1039d48e/src/polyfill-wrapper-end.js#L15-L16

**Comment by MajorBreakfast** [comment]
@guybedford Sorry for all this iOS 7 web worker crap BTW :) There's a good chance that after this one everything finally works, tough :P

**Comment by guybedford** [comment]
Included in master, with a build. Note that for the `console.assert`, this is minified out, so you won't get that issue against the minified source.

Can you let me know if that's working ok, then I'll post out a release?

**Comment by MajorBreakfast** [comment]
@guybedford Can you include the fix for `console.assert` as well? Reason is that in sometimes switch to the src version to get a meaningful output (stack trace and line number).

**Comment by MajorBreakfast** [comment]
@guybedford Just tested it. Now everything works without hacks.

**Comment by guybedford** [comment]
Thanks! The `console.assert` stuff gets a bit hairy to support in IE8, so we can reassign it etc unfortunately.

**Comment by MajorBreakfast** [comment]
Hmm, didn't know that. Anyway, thanks for solving this :)
