### ISSUE TITLE
Should the loader respect the base tag?

### ISSUE THREAD

**Issue by MajorBreakfast** [ModuleLoader/es6-module-loader#364]
I've just discovered that the base tag isn't taken into account by the module loader. This issue isn't a bug report, I'm just wondering what your thoughts are on this: Should the module loader resolve relative URLs the same as script tags do?

Here's an example:
```HTML
<base href="/my-app-root/">
<script src="es6-module-loader.js"></script><!-- Loads /my-app-root/es6-module-loader.js -->
<script>
  System.import('main') // Loads /main.js
</script>
```

The use of a base tag is quite common in modern web applications that use push state routing. This issue is inspired by the base tag discussion in [this SystemJS issue](https://github.com/systemjs/systemjs/issues/290).

**Comment by guybedford** [comment]
This is implemented in SystemJS, and has been moved to the module loader in the 0.17 branch (https://github.com/ModuleLoader/es6-module-loader/commit/0a29fcb0dda8e9b43fc2aa11c5c812a1a7c73f6f).

**Comment by MajorBreakfast** [comment]
Alright! :)
