### ISSUE TITLE
Firefox: mutating the [[Prototype]] of an object

### ISSUE THREAD

**Issue by szepeviktor** [ModuleLoader/es6-module-loader#365]
At line https://github.com/ModuleLoader/es6-module-loader/blob/master/dist/es6-module-loader.src.js#L2656
```
mutating the [[Prototype]] of an object will cause your code to run very slowly;
instead create the object with the correct initial [[Prototype]] value using Object.create
```
Is it a very low inportance warning from Mozilla?

**Comment by guybedford** [comment]
This is output from esnext - it's actually been changed in the 0.17 branch which will be landing soon.

**Comment by szepeviktor** [comment]
Thank you!
Yes it is Firefox 39.0a2 (2015-04-07).
