### ISSUE TITLE
Crashes if traceur.js or babel.js are not included

### ISSUE THREAD

**Issue by speigg** [ModuleLoader/es6-module-loader#367]
Documentation states:

```html
If using ES6 syntax (optional), include traceur.js or babel.js in the page first then include es6-module-loader.js:

  <script src="traceur.js"></script>
  <script src="es6-module-loader.js"></script>
```

However, just using: 
```html
  <script src="es6-module-loader.js"></script>
```

Results in:

```console
GET http://localhost:8080/traceur.js 404 (Not Found)
Potentially unhandled rejection [5] Error loading "main" at http://localhost:8080/main.js
Error loading "traceur" at http://localhost:8080/traceur.js
Not Found: http://localhost:8080/traceur.js (WARNING: non-Error used)
```

**Comment by speigg** [comment]
FYI, I was trying to use babel/babel-connect to convert from es6 to es5 on the server-side, and only use the following in my html file:

```html
<script src="es6-module-loader.js"></script>
<script>
System.import('main')
</script>
```

**Comment by guybedford** [comment]
The module loader here on its own doesn't support loading anything except ES6.

You need to extend the loader to understand an ES5 module format (like System.register, CommonJS, AMD or globals) before you can expect this to work.

See https://github.com/ModuleLoader/es6-module-loader/wiki/Production-Workflows#systemregister-output if you're looking for a minimal extension method.

**Comment by speigg** [comment]
Okay. So what does the documentation mean when it says that traceur.js or babel.js are optional?

**Comment by guybedford** [comment]
That you can write a loader that doesn't have to use them in production, making the loader production-suitable.
