### ISSUE TITLE
Relative parent path resolve fails if path starts with ./

### ISSUE THREAD

**Issue by hlege** [ModuleLoader/es6-module-loader#368]
We have a genereated requirejs based code concatenated with r.js. r.js uses ./.. format for relative parent paths. Because of the leading ./, es6-module-loader will throw an "Illegal module name" error.

**Comment by guybedford** [comment]
Sure, I've ensured that this will be supported in the next release that contains the new normalization algorithm.

**Comment by hlege** [comment]
Thank you!
