### ISSUE TITLE
System.register Explained clarifications

### ISSUE THREAD

**Issue by dchambers** [ModuleLoader/es6-module-loader#371]
Hi @guybedford,

I'm [trying to spike](https://github.com/dchambers/es6-module-loader-spike) whether [BRJS](http://bladerunnerjs.org/) could use `System.register()` as a common bundling format for both NPM and BRJS source code, and the problem I'm having is that I'm struggling to really comprehend the [System.register Explained page](https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained), and feel like I'm completely misunderstanding how it works and/or what it's purpose is.

It states:

> System.register can be considered as a new module format designed to support the exact semantics of ES6 modules within ES5.

Yet some points of immediate confusion for me are:

  * Why does `System.register()` allow the `name` argument to be omitted (which `babelify` actually does for example), since then I can't understand how `System.import()` could subsequently be used to retrieve the module?
  * Why is `System.register()` only invoked once even though I only have two modules in my spike  &mdash; is it being invoked once per bundle?
  * Could `System.register()` be invoked multiple times with different bundles &mdash; you talk elsewhere about _zebra striping_ being used for different module formats, so is this within a single unified bundle, or can multiple `System.register()` invocations be used?
  * How should `System.import()` be invoked after `System.register()` has been used to register a bundle, as for me it fails with `Potentially unhandled rejection [3] Error loading "A" at http://localhost:8080/A.js` since it tries to reload module `A`, rather than using the one that was previously registered with `System.register()`?

Perhaps the answers to these questions can be fed back into the [System.register Explained page](https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained) to provide better context for other people in the same position as me?

**Comment by probins** [comment]
if you look at Babel's docs http://babeljs.io/docs/usage/modules/ does that example help? It converts `import`/`export` into a function which current browsers can understand (like amd/cjs) but in a form that the loader polyfill can use directly

**Comment by dchambers** [comment]
Hi @probins,

Yes, the example you mention actually makes sense to me since the `System.register()` invocation has a `name` argument:

```js
System.register("bar", ["foo"], function (_export) {
  "use strict";

  var __moduleName = "bar";

  var foo;
  function bar() {
    return foo("foobar");
  }
  return {
    setters: [function (m) {
      foo = m.default;
    }],
    execute: function () {
      _export("bar", bar);
    }
  };
});
```

presumably because the module being exported is named `bar`:

```js
import foo from "foo";

export function bar() {
  return foo("foobar");
}
```

OTOH, the example shown in the [System.register Explained page](https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained) and what I see when I use babelify is that the `name` argument is omitted. There is even code within SystemJS for handling this case, so it's definitely intentional ... but confusing!

**Comment by dchambers** [comment]
I created a [synthetic-bundle-test](https://github.com/dchambers/es6-module-loader-spike/tree/synthetic-bundle-test) branch within my spike, based on the example from the Babel documentation, and everything now works as I'd originally expected. So I guess my questions relate more to stuff like 'babelify' that only do a single nameless `System.register()` invocation, rather than code like what I have within my new spike that invokes `System.register()` once per module.

**Comment by probins** [comment]
ES6 modules do not name themselves, like Node modules, so if you're transpiling separate modules, System.register will not have names. I've not used babelify, but assume that's what it's doing. The situation is different when you're bundling, as each module within the bundle has to be identified.

**Comment by guybedford** [comment]
@dchambers the **anonymous** System.register is preferable for non-bundled separate-file transpilation. When each file is transpiled separately, there can be one call per module, without a name, so that the module name can still be set by the enviornment instead of internally. That is the transpilation process doesn't need to have ay knowledge of the naming system assumed by the loader environment, making it a more general and portable transpilation, whereas bundles do.

**Comment by dchambers** [comment]
> ES6 modules do not name themselves, like Node modules

Hi @probins, these ES6 modules are Node modules, and have exactly the same names they would have if I wrote them in ES5, and used browserify alone, without using babelify to allow transpilation. Maybe this is a babelify bug?

**Comment by dchambers** [comment]
> 

> the anonymous System.register is preferable for non-bundled separate-file transpilation. When each file is transpiled separately, there can be one call per module, without a name, so that the module name can still be set by the enviornment instead of internally.

@guybedford, but in that case it's still not clear to me how I can use an anonymous module if there is no name for me to refer to it with in `System.import()`, and given that the contents of the module aren't executed immediately either it seems unusable?

Additionally, my spike is using browserify+babelify to _bundle_ up a number of modules (2 in my case), so it's not the case that these are single modules that are being transpiled, whereas it definitely should be a bundle of modules.

I think I'm still lacking some important piece of information that's obvious to you, but which I don't have knowledge of yet...

**Comment by probins** [comment]
> it's still not clear to me how I can use an anonymous module if there is no name for me to refer to it with in System.import()

you map the name to the location of the file you want to load, using System.paths in the current spec, site.mappings in the new one. So your app says `import ... from x`, and your mappings tells the loader where to find 'x'; one site might load this from a relative url, another might prefer to fetch from an external cdn. System.import is for dynamic loading, and follows the same principle `System.import('x')` and use mappings to determine where 'x' is located.

**Comment by dchambers** [comment]
>> it's still not clear to me how I can use an anonymous module if there is no name for me to refer to it with in `System.import()`

> you map the **name** to the location of the file you want to load, using `System.paths` in the current spec, `site.mappings` in the new one. 

Sorry, but how can I map a name to a file location if there is no name because the module is anonymous? For example, the example you provide talks about  a module called `x`, whereas babelify gives me an anonymous module with no name?

**Comment by probins** [comment]
look at the demo for an example. index.html imports test1 and test2. The default is that this maps to './test1.js' but you can map it to fetch abc.com/xyz.js if you prefer. The modules are anonymous; they do not include any 'my name is test1' statement.

Bundling is a separate issue. The solution that babel/traceur and this loader polyfill have come up with is to provide an id in System.register for each module in the bundle. But this is temporary, as System.register will go away once browsers support import/export. How modules will be bundled in the future remains to be seen. http://w3ctag.github.io/packaging-on-the-web/ is a recent proposal.

From a brief look at babelify source, it looks to me like they are not currently handling module bundles, so you may need to raise this with them.

**Comment by dchambers** [comment]
Hi @probins,

Thanks for coming back to me to so quickly again, and thanks for making me aware of the _packaging on the web_ proposal, that I wasn't previously aware of.

I've just tried running the demo you mentioned, which although very cool given that it transpiles inside the browser, doesn't seem related to the question I've been asking about how anonymous modules can be used. In the demo, `test1` and `test2` are imported, but that just causes the browser to fetch these from the web-site at `test1.js` and `test2.js`. And, both of these are just plain JavaScript files, and are not anonymous modules using `System.register`. AFAICT, no anonymous `System.register` modules anywhere in sight.

I guess what I'm trying to understand is, given the anonymous module mentioned in the [System.register explained page](https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained#how-it-works) has been loaded within the browser:

```js
System.register(['./dep'], function($__export) {
  var s, C, q;
  function func() {
    return q;
  }
  $__export('func', func);
  return {
    setters: [
    // every time a dependency updates an export, 
    // this function is called to update the local binding
    // the setter array matches up with the dependency array above
    function(m) {
      q = m.p;
    }
    ],
    execute: function() {
      // use the export function to update the exports of this module
      s = 'local';
      $__export('C', C = $traceurRuntime.createClass(...));
    }
  };
});
```

how is it now possible for me to cause that code (i.e. `q = m.p`) to be either executed _or_ imported _or_ both?

**Comment by probins** [comment]
it is executed by the loader the first time it is imported, and then stored in the loader's registry to be used in any further imports. Take the demo test1/2. In a typical app, you might have your source files in lib/ or src/, and your production builds in dist/, but for a simple test, just rename test1.js to test1.src.js, convert to register() calls with `babel --modules system test1.src.js -o test1.js` and then reload index.html.

I looked up the module naming for bundles for you, and you have to specify `--module-ids true` as an option to `babel`. If you specify this in your babelify command, it should then output ids within the bundle.

**Comment by guybedford** [comment]
@dchambers the normalized module name is taken to be the path within the baseURL which is by default the window.location. `System.import('jquery')` would load `jquery.js` at the current page path and then if anonymous that module is stored in the registry as `jquery`.

**Comment by dchambers** [comment]
> `System.import('jquery')` would load `jquery.js` at the current page path and then if anonymous that module is stored in the registry as `jquery`.

Okay, I think finally get it!

Anonymous modules can't be pre-emptively sent to the browser, and must be loaded as a result of an import statement, which effectively names them. Named modules can be pre-emptively sent to the browser en-masse, which is referred to a _bundling_, and which is why `System.register()` can therefore also be considered to be a bundling format?

**Comment by dchambers** [comment]
@guybedford / @probins, given what I now know, I think that adding a new _Bundled Vs On-Demand_ section between the _How it works_ and _Limitations_ sections with something like the follwing content would do a lot to help provide some missing context for other readers in the future:

### Bundled Vs On-Demand

`System.register` has the type signature:

```js
System.register([name, ]dependencies, module)
```

Each invocation to `System.register()` allows a single module to be defined. If `name` is provided then it's a named module, and a bundle of modules (containing multiple `System.register()` invocations) can be pre-emptively sent to browser before `System.import()` is ever invoked. If name is omitted then it's an anonymous module, and it can only be sent to the browser in response to a `System.import()` invocation, in which case the name of the module will be the same as the name of the argument provided to `System.import()`.

**Comment by probins** [comment]
> it can only be sent to the browser in response to a System.import() invocation

System.import is for dynamic import, for example, user clicks on button saying 'I want to do x', and it fetches the code for x (test2 in the demo). In a static app/page, where you load everything up front, you wouldn't use System.import: modules will be loaded in response to the first `import` request from another module. You can preload modules in a bundle, so load the whole app at once, but you can also preload with, for example, SystemJS's depCache https://github.com/systemjs/systemjs/wiki/Configuration-Options which also removes excess http requests but is more flexible than bundling and gives additional advantages wrt caching.

**Comment by dchambers** [comment]
> System.import is for dynamic import, [...]

You're talking about the **polyfill** rather than native behaviour right, since my understanding is that `import` statements will use `System.import()` beneath the covers when this is done natively, and so in the long term `System.import()` will be used for all importing that needs to be done?

For the **polyfill** though, where `System.import()` is only ever used for dynamically importing modules, then we are effectively saying that anonymous modules are only of use for dynamically loaded modules?

**Comment by guybedford** [comment]
@dchambers thanks for these points, I completely agree this needs to be explained. I've updated https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained along the lines of your suggestions.

**Comment by dchambers** [comment]
Lovely, thanks @guybedford :+1:

**Comment by MajorBreakfast** [comment]
> but you can also preload with, for example, SystemJS's depCache

@probins I hope you don't mind me doing a bit of nitpicking, but using depCache isn't really "preloading" since you don't fetch anything beforehand.

> import statements will use System.import() beneath the covers when this is done natively

@dchambers I don't think so. The method itself won't be called. It goes through all the loader hooks, though. @guybedford can you confirm?

> anonymous modules are only of use for dynamically loaded modules

They're no good for bundles. But dynamically or not the format (es6, cjs, amd, anonymous register) doesn't matter.

**Comment by dchambers** [comment]
@MajorBreakfast, thanks for the clarifications, it's good to know how this stuff really works.

**Comment by probins** [comment]
> using depCache isn't really "preloading" since you don't fetch anything beforehand

to be absolutely precise, it's most useful with http/2 where the server supplies the files without them having to be separately requested - bundling without the bundle as it were :-)

**Comment by probins** [comment]
@dchambers the aim of the polyfill is to create the same environment as when this stuff is supported natively. It's not 100% but the basic flow should be identical. You should be able to write your app now as though import/export and the loader are natively supported, use babel/traceur to convert import/export to System.register, and the polyfill to supply the loader. Then, once native support is there, you simply remove those steps. Many apps will never need to refer to the System object (or Reflect.loader or whatever).

**Comment by dchambers** [comment]
@probins, yes, good point. I was just using `System.import()` as a proxy for explaining how anonymous modules can ever be used, but I probably should have said "processing `import` statements" instead, since this is a far more common use case.

**Comment by PavelPZ** [comment]
I am very sorry for maybe stupid question:

#### My situation:
- I have .JS bundle with many named System.register("???",... modules
- one of this modules contains entry point of angular2 application (```bootstrap(app.AppComponent...```)
- I use both ```system-polyfills.js``` and ```system.src.js``` libraries

#### Question:
- if I import this file dynamically (```System.import(...```), how to say to SystemJS, which module to execute as starting point?
- if I include this file statically (by means of ```<script>``` tag), situation is similar: none of my code is actually called.

**Comment by bennyn** [comment]
Looks like the page https://github.com/ModuleLoader/es-module-loader/wiki/System.register-Explained is gone. :cry: 

Can anybody tell me where to find it now?

**Comment by probins** [comment]
https://github.com/ModuleLoader/es-module-loader/blob/master/docs/system-register.md
