### ISSUE TITLE
Debugging in chrome often hits eval files.

### ISSUE THREAD

**Issue by QuantumInformation** [ModuleLoader/es6-module-loader#372]
I have a project where the debugger is often hitting the main.js!eval file instead of main. However for imported files via main.js the debugger hits the correct non eval files. 

```js
  <script>
    System.transpiler = 'babel';
    System.import('app/main').then(function (m) {
      new m.Main();
    });

  </script>
```

**Comment by guybedford** [comment]
Yes this is a quirk of the source maps behaviour.

**Comment by QuantumInformation** [comment]
Closing as its related to sourcemaps.
