### ISSUE TITLE
Support loading in a Service Worker

### ISSUE THREAD

**Issue by matthewp** [ModuleLoader/es6-module-loader#374]
I think this would work if https://github.com/ModuleLoader/es6-module-loader/blob/master/src/system.js#L64 checked for global.fetch and used that.

**Comment by guybedford** [comment]
Does XHR not work inside of service workers?

**Comment by OliverJAsh** [comment]
How would we download and execute SystemJS in a service worker at all?

**Comment by matthewp** [comment]
@guybedford I believe not, it's hitting the `throw` in this case.  Eventually all environments will support `fetch` so it would be nice to make that the default anyways.

@OliverJAsh You can execute any script as a service worker, so that includes es6ml.  You might want to bundle it with some other script that calls `System.import` if you want it to actually do something though.

**Comment by guybedford** [comment]
Ok, sure, yes it makes sense to use `fetch` if its supported as an API here anyway.

**Comment by guybedford** [comment]
I believe support for this was added in https://github.com/ModuleLoader/es6-module-loader/pull/448.
