### ISSUE TITLE
.js extension added, even when exists

### ISSUE THREAD

**Issue by omerts** [ModuleLoader/es6-module-loader#376]
Hello,

When importing a path already ending with ".js", another ".js" extension is concatenated to the end of the path, which causes the file to not be found.

Omer

**Comment by guybedford** [comment]
Yes, this is by design, but it is being removed as a feature in the next release.

**Comment by omerts** [comment]
@guybedform, from the other side, when the '.js' concatenation is dropped, could we still use import without specifying an the '.js' extension? 
For example:
```javascript 
System.import('index'); // Expecting index.js to be imported
```

**Comment by guybedford** [comment]
Yes, the release notes will describe fully the different ways of achieving this.

**Comment by omerts** [comment]
Thanks for the super fast response. Has this feature been removed already? 
I am using it like this:
```javascript
<!DOCTYPE html>
<html>
<head>
  <title>Phoenix</title>
</head>
<body>
  <div id="app">
    Root component mounts here.
  </div>
  <script src="node_modules/babel-core/browser.js"></script>
  <script src="system.js"></script>
  <script type="text/babel">
    System.map['css'] = 'css.js';
    System.transpiler = 'babel';
    System.import('index.css!');
    System.import('index');
  </script>
</body>
</html>
```
I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/4996164/7748449/688ed462-ffcd-11e4-9f0b-a97e89a49906.png)
(.js is not concatenated)

**Comment by timbur** [comment]
How long until next release?  In the mean time, how can it be fixed so that when external packages `require('somefile.js')`, it doesn't get `somefile.js.js`?

**Comment by guybedford** [comment]
If installing a package from npm, jspm will ensure this behaves correctly by converting it statically.

A workaround is to set `System.paths['github:project/name@x.y.z/*'] = ['*']` which should override the automatic js adding.

**Comment by timbur** [comment]
I see.  So is my problem because I'm using `jspm install` for packages only intended for the client?

> `System.paths['github:project/name@x.y.z/*'] = ['*']`

This works beautifully.  Thank you!  Will this be something I'll need to use indefinitely?  Based on what I've read so far, I'm unclear on this.

**Comment by guybedford** [comment]
If the sources are ES6 then at least until the next configuration upgrade allows extensions like this.

If the sources are CommonJS, you can load the project as an npm repo to get the npm conversions with `registry: 'npm', jspmNodeConversion: true` in the package.json.

**Comment by timbur** [comment]
I ended up having to do this, due to inconsistent naming conventions within the external package:
```
"github:nodeca/pako@0.2.6/*.js": 'jspm_packages/github/nodeca/pako@0.2.6/*.js'
```

**Comment by timbur** [comment]
> If the sources are CommonJS, you can load the project as an npm repo to get the npm conversions with registry: 'npm', jspmNodeConversion: true in the package.json.

I see.  Thanks.  I'm building some in-browser tools that will allow developers to pull packages from nearly any source on-the-fly, all (or mostly) client-side, so I'm not sure how feasible it would be to rely on the npm conversion.
