### ISSUE TITLE
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

### ISSUE THREAD

**Issue by capaj** [ModuleLoader/es6-module-loader#380]
Just noticed, that in Firefox 35.0.1 and 38.0.1 I have this warning in the console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create                es6-module-loader.js:7:27734
``` 

Maybe nothing, but considering you probably don't run it in FF that often, it might be useful to know.

**Comment by guybedford** [comment]
This may have been resolved in the latest master branch as we altered the way we handle classes. I just tested it and we still get the issue within Traceur not the module loader from my tests. But it doesn't show up for SystemJS as far as I can tell, but do let me know if I've overlooked something.
