### ISSUE TITLE
Byte Order Mark included in fulfilled string from SystemLoader.fetch when executed in node

### ISSUE THREAD

**Issue by jonoward** [ModuleLoader/es6-module-loader#388]
When SystemLoader.fetch is executed on node, if the source file is UTF-8 and has a BOM, this is not stripped out by default (see https://github.com/joyent/node/issues/1918). This is causing an issue in systemjs-builder, when minification is enabled, and the plugin-text is used, as the BOM gets encoded, so you land up with strings like:

`"\ufeff<div>hello</div>"`

I'll submit a PR for this shortly

**Comment by guybedford** [comment]
@jonoward thanks again for this.
