### ISSUE TITLE
baseURL not prepending in 0.17

### ISSUE THREAD

**Issue by milesj** [ModuleLoader/es6-module-loader#394]
Just upgraded to version 0.17 and started updating my code to support the recent changes, mainly the automatic JS extension portion. However, I've noticed that my `System.baseURL` setting is no longer working. 

In my setup, I have `System.baseURL` set to `/base/js-es6/` (to support Karma paths). As an example, say I have a file `foo.js` that has an `import Bar from 'bar'`. This `bar` will be resolved to `bar.js` and the loader will attempt to load it at the following address http://localhost:9876/bar.js. This is wrong, as it should load from http://localhost:9876/base/js-es6/bar.js.

Is there an extra step I need to take to support the 0.17 changes? Or is this a bug that was introduced?

**Comment by guybedford** [comment]
@milesj yes baseURL has been removed from this implementation.

Instead you can use the wildcard path here - `System.paths['*'] = '/base/js-es6/*'`.

baseURL is only a feature of SystemJS now as it was removed from the spec.

**Comment by milesj** [comment]
It wasn't mentioned in the changelog on the release and was still mentioned within the readme/wikis. I'll give it a whirl using `paths`, thanks!

**Comment by probins** [comment]
see #395
