### ISSUE TITLE
URL use errors in IE/Edge

### ISSUE THREAD

**Issue by jdalton** [ModuleLoader/es6-module-loader#398]
The URL constructor in IE/Edge exists but cannot be called as a constructor. So the [feature inference](https://github.com/ModuleLoader/es6-module-loader/blob/39b2732cf38677a444aad1a2fbdaaf9c0363f3d5/src/wrapper-start.js#L85) of "function" passes and then errors out when used.

**Comment by guybedford** [comment]
Thanks! Is there an alternative you would suggest? Is there a better way to call it in Edge?

**Comment by jdalton** [comment]
I think modifying the feature check from:
```js
var URL = typeof __global.URL == 'function' && __global.URL || URLPolyfill;
```
to
```js
try {
  var URL = (new __global.URL('http://')).protocol == 'http:' && __global.URL;
} catch(e) {
  URL = URLPolyfill;
}
```

**Comment by guybedford** [comment]
Thanks, the build in this project actually always uses the polyfill directly - it's just SystemJS that loads it as a separate step. Mainly because there is a lot of pressure to show a low footprint loader.

Fixed this up in SystemJS at https://github.com/systemjs/systemjs/commit/47d9bf0b9b74bded2fba0cb151f1300ef5dfeff4.

**Comment by probins** [comment]
strange: according to https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility the URL constructor is supported in IE from v10. Is that not correct?

**Comment by jdalton** [comment]
While the `URL` function exists calling it as a constructor, a relatively newer addition, is not supported yet.

**Comment by probins** [comment]
ah yes, right, that's this page https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
