### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by nordisk** [ModuleLoader/es6-module-loader#400]
Hi.

When I try to run the demo, I get the following error:

```js
GET http://localhost:63342/es6-module-loader-master/demo/test2 404 (Not Found)s @ es6-module-loader.src.js:1123(anonymous function) @ es6-module-loader.src.js:1156g.fetch @ es6-module-loader.src.js:1155(anonymous function) @ es6-module-loader.src.js:310

index.html:1 Uncaught (in promise) Not Found: http://localhost:63342/es6-module-loader-master/demo/test2
	Error loading http://localhost:63342/es6-module-loader-master/demo/test2
```

Any ideas?

**Comment by guybedford** [comment]
The demo needs to be updated - `.js` extensions are no longer added automatically. Extensions should always be included now or paths configuration used to alias names with an extension.

**Comment by nordisk** [comment]
Just noticed that. When I add ```.js``` it works for me. Do you want me to update the demo?

But I get another error when changing to ```.js```

```js
Error: transpile is not defined
	Error loading http://localhost:63342/object-position/test/mm.js
    at http://localhost:63342/object-position/node_modules/es6-module-loader/dist/es6-module-loader.js:7:4362
```

**Comment by guybedford** [comment]
That would be a great help if you can send a PR. Yes it should be `es6-module-loader.dev.js` for in-browser transpilation.

**Comment by guybedford** [comment]
Also created https://github.com/ModuleLoader/es6-module-loader/issues/401.

**Comment by nordisk** [comment]
Cheers. Just forked and will resolve the demo bug. Works fine for me now! Thx.
Will look into #401 as well.

**Comment by nordisk** [comment]
What is really weird is that I have to import test1 as:

```js
<script type="module">
    import { hello } from 'test1.js';
```
Otherwise it ```404```'s

**Comment by guybedford** [comment]
Yes - this is correct in the latest spec for resolution via URLs.

**Comment by nordisk** [comment]
Oh – I was reading the final es2015 spec and couldn't find any mention of file extensions.
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf p.276

**Comment by guybedford** [comment]
The ES specification doesn't define what specifiers are. The loader specification handles that - https://github.com/whatwg/loader.
