### ISSUE TITLE
Throw better error for production loader transpile

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#401]
This can be done via a simple transpile throwing function in `dynamic-only.js`. The hard part is working out exactly what use cases would give this error and how best to advise the user.

**Comment by nordisk** [comment]
I just started to examine ```dynamic-only.js```.
My IDE is throwing some errors on these lines https://github.com/ModuleLoader/es6-module-loader/blob/master/src/dynamic-only.js#L34-L35

Running ```lint``` task reports 0 errors. Weird.
