### ISSUE TITLE
`Unexpected token :` in dev map

### ISSUE THREAD

**Issue by rblakeley** [ModuleLoader/es6-module-loader#405]
I'm getting this error in the browser console:
`Uncaught SyntaxError: Unexpected token :` in `es6-module-loader-dev.js.map:1`

I just did `npm install es6-module-loader` and moved that file from `node_modules/es6-module-loader`into a `vendor/js` directory. Then I have `<script src="js/vendor/es6-module-loader-dev.js.map"></script>` in my html doc.

So is there a typo or bug in that distributed file?

**Comment by guybedford** [comment]
Make sure you reference the js file ending in js. The source map file will
be used automatically if present.

Alternatively just use es6-module-loader.src.js for the best debugging
experience.

**Comment by guybedford** [comment]
Let me know if you need further help here.

**Comment by rblakeley** [comment]
@guybedford got it. thanks.
