### ISSUE TITLE
system-register-only link in production-workflows.md

### ISSUE THREAD

**Issue by peteruithoven** [ModuleLoader/es6-module-loader#406]
Currently the *system-register-only* link in the [production-workflows.md](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/production-workflows.md) is broken. Not sure how to fix it though? 
It tries to link to the dist folder of a *v0.17.0* branch, which doesn't exist. There is a *0.17* branch, but this doesn't include a *system-register-only.js* file. (There is a *system-register-only.js* file in the *master* branch.)

**Comment by guybedford** [comment]
Thanks for reporting this, I've fixed the link in https://github.com/ModuleLoader/es6-module-loader/commit/390585bad29b56dbd4d9e5be376dd42cda1b66fc.
