### ISSUE TITLE
Importing module that imports something else doesn't work.

### ISSUE THREAD

**Issue by Clemmy** [ModuleLoader/es6-module-loader#407]
Hey guys, I'm not sure if this is a bug or I am using it incorrectly. The scenario is that I am trying to import a module, say, ```foo.js``` with 
```
//example.js
System
  .import('foo.js')
  .then(function(stuff) {
    console.log(stuff);
  });
```
where my foo.js looks like:
```
//foo.js
import fs from 'fs'; //works if this line is taken out
export default function () { console.log('bar'); };
```
I run the script with ```babel-node example.js```. The callback is never called, as far as I know, but it works when I remove the import statement in foo.js. Can someone clarify this for me? Thanks!

**Comment by guybedford** [comment]
`node-babel` is a separate project to the module loader work. To use `System` you need to import it as a NodeJS module itself, but then it wouldn't be using node-babel. I'd suggest either using all ES6 with node-babel or all ES6 with System.

**Comment by Globegitter** [comment]
I am running into the same issue. I have 3 files:

```
// index.js
'use strict';

require("babel/register")({
  stage: 0
});

let NextServer = require('./server.js');
let server = new NextServer();
server.start();
```

```
// server.js
import {System} from 'es6-module-loader';
import http from 'http';

System.transpiler = 'babel';

...
let UserResource = await System.import(`./app/test.js`);
...
```

```
app/test.js
import Resource from '../src/Resource'; // if I take that out all works fine

export default class Cards {
  get() {
    return 'Wooohhhhooo this is the get function!';
  }
}
```

Using iojs 2.3.4 via `node index.js`. Any idea what the issue could be? Is it also babel and `System` interfering with each other?

**Comment by guybedford** [comment]
What error message are you getting here? Note that you need to include file extensions on the imports - `import Resource from '../src/Resource.js'`.

**Comment by Globegitter** [comment]
ah yeah that was it! It didn't show any error though. The promise never seemed to resolve. Is there a reason that we need to specify the '.js'? I I have seen some other usages of the of ES6 modules where the '.js' could be left out.

**Comment by guybedford** [comment]
There definitely would have been an error - check that your code is rejecting correctly. This was a recent breaking update to use the extension, as part of aligning with the new guidelines. See https://github.com/ModuleLoader/es6-module-loader/releases/tag/v0.17.0.

**Comment by Clemmy** [comment]
Hey guybedford, I am still running into the problem with v0.17.3. I am using es6-module-loader along with babel because I need to load modules with dynamic paths, which ES6 imports don't support.

**Comment by guybedford** [comment]
@Clemmy it is probably worth sticking with just node-babel here and not using the module loader - `node-babel foo.js` say.

**Comment by Clemmy** [comment]
But I need to load modules at runtime, since in my situation, I don't have the filepaths of the modules I want to load at execution time. I looked into it a bit deeper, and notice a ```[Error: ENOENT, open '/Users/clementhoang/Workspace/mappedin/titan/src/tools/fs']``` when I catch and output the error.

**Comment by guybedford** [comment]
The loader won't do the Node lookup algorithm though so isn't compatible with doing this type of app, unless explicitly extending it with the Node resolution algorithm. I don't yet know of any project that does that.

**Comment by Clemmy** [comment]
Alright, thanks a lot! I resorted back to using CommonJS requires for now.
