### ISSUE TITLE
System.import() v0.17.x

### ISSUE THREAD

**Issue by dbabaioff** [ModuleLoader/es6-module-loader#408]
On version 0.16.x, following this doc page - production workflow (https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/production-workflows.md).
If I include a js file transpiled using Babel with ```modules=system``` on my page, then call ```System.import```, systemjs will not make an ajax request to load my js file - because it's already included on my page - works fine.
For example, lets say:
```js
System.register('boot.js', [], function (_export) {
   ...
}); 
```
And on my page:
```js
System.import('boot.js')
```
But, on version 0.17.x I include the same file and systemjs always make an ajax request to load my file. How can I avoid this? like version 0.16

**Comment by guybedford** [comment]
It's best to always use anonymous System.register output of the form:

```javascript
System.register([], function (_export) {
   ...
}); 
```

Named System.register is only for bundles where there are multiple modules in a single bundle file.

It can work with named register statements, but then it requires deep knowledge of the normalize system to ensure that the names perfectly match up.

**Comment by guybedford** [comment]
Let me know if you need further help here.

**Comment by jonricaurte** [comment]
@guybedford I am running into the same issue. The nice thing about having it named is I could load up everything in one file and then import my application.js which would start the importing process for all my other system registers. How would I import a specific register that is anonymous? I am using an angular 1 build and here is a sample gulp task:

```
gulp.task('combined-js-slim', ['js','slim'], function() {
  return gulp.src(['public/assets/dependencies.js', 
                   'public/assets/templates.js',
                   'jspm_packages/npm/babel-core@5.8.22/browser.js',
                   'jspm_packages/github/ModuleLoader/es6-module-loader@0.17.7/es6-module-loader-dev.js',
                   'jspm_packages/system.js',
                   'config.js',
                   'public/assets/application.js'])
    .pipe(concat('app.js'))
    .pipe(insert.append("System.import('application.js')"))
    .pipe(gulp.dest('public/assets'));
```
I first load in my dependencies using an sfx bundle. My templates are then loaded using ngHtmlToJs. the application.js is my actual app. I concat them all into one file and then at the end import my app. There doesn't seem to be a way to do this with the latest versions. I'm using babel transpiling in a gulp task:
```
gulp.task('js', function () {
  return gulp.src('app/assets/javascripts/**/*.js')
    .pipe(plumber())
    .pipe(cache('scripts'))
    .pipe(babel({ 
      modules: 'system', 
      moduleIds: false,
      getModuleId: function (name) {
        return name + '.js';
      }
    }))
    .pipe(remember('scripts'))
    .pipe(concat('application.js'))
    .pipe(gulp.dest('public/assets'));
});
```
When I load the page, I get this error: Uncaught TypeError: Invalid anonymous System.register module load. If loading a single module, ensure anonymous System.register is loaded via System.import. If loading a bundle, ensure all the System.register calls are named.

When I change moduleIds:true, it tries to make an ajax call. So the questions is, how would I make it import a specific register like it used to do using anonymous registers?

Thanks! Also @dbabaioff was wondering what you ended up doing? It seems like this should be documented somewhere.

**Comment by guybedford** [comment]
@jonricaurte when concatenating multiple modules in the same file, you need to use names certainly. It's only when compiling files and leaving them as separate files that it is best to keep modules anonymous. That is because as soon as you include names, you are reducing portability and making the code environment specific as it is including linking information.

**Comment by jonricaurte** [comment]
@guybedford Thanks for the update. Was wondering why it is not possible to use System.import in the same file as the registered name. An example would be after the files are concatenated into one file, the file looks like this:

```
System.register('application.js',[], function(){
    //code
});
System.import('application.js');
```
With older versions, I was able to import the register even if it was in the same file and there would be now ajax call made, however, with newer versions it actually tries an ajax request to localhost:3000/application.js. Is there a way to make it so System.import does not make an ajax request if the name is already registered within the same file?

Thanks!

**Comment by guybedford** [comment]
@jonricaurte is the above with the register extension only? The way to check is to see that `System.normalize('application.js').then(console.log.bind(console))` matches the exact URL name string as the one registered at `Object.keys(System.defined)`.

**Comment by jonricaurte** [comment]
@guybedford Thanks for the update! Will try it out and let you know what I find.
