### ISSUE TITLE
Import from node_modules

### ISSUE THREAD

**Issue by Globegitter** [ModuleLoader/es6-module-loader#411]
I am importing a file `let UserResource = await System.import(`./app/cards.js`);` which in turn imports (or wants to import) from an installed node_module. 

I thought `import {Resource} from 'nord';` would do the trick, but then I am getting error `[Error: ENOENT: no such file or directory, open '/path-to-app-root/nord']`. Is there any way to let it look in node_modules instead?

**Comment by guybedford** [comment]
A custom loader would need to be built from this to handle the Node-resolution. It can be done though as a project for someone interested to build a Node-style loader based on this project.

**Comment by Globegitter** [comment]
How come that imports for default node modules, such as http etc work? But in any case, do you have any pointers to some docs or pieces in the code that could help implementing a node-style loader? Might try to take a stab at it.

**Comment by guybedford** [comment]
`http` imports certainly wouldn't work here. There's some info on creating a custom loader at https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here at all.
