### ISSUE TITLE
Module IDs starting with a dot are not expanded using System.paths

### ISSUE THREAD

**Issue by ondras** [ModuleLoader/es6-module-loader#412]
I am using the following
```js
System.paths["*"] = "/js/es6/*.js";
```
to serve my JS files from a given prefix. However, ```import from './module'``` is resolved incorrectly, without the **.js** suffix. The ```"./module"``` syntax is correct, as far as I know.

Is this the correct behavior? I do not want to specify file extension in my ```import``` statements. Shall I switch to custom ```System.locate``` impl?

**Comment by guybedford** [comment]
It is no longer supported to use paths to set default extensions. Rather use a custom normalize / locate hook.

**Comment by guybedford** [comment]
Also yes paths only apply for non-relative URLs.

**Comment by ondras** [comment]
@guybedford thanks for a reply. To clarify:

1) path prefix shall be done via ```System.locate```,
2) .js extension added via ???

Are these two covered somewhere in the revelant spec?

**Comment by guybedford** [comment]
@ondras the spec encourages the convention to write modules with js extensions included - `import 'file.js'`. Path prefixing is fine to do via paths, but adding extensions needs to be done via a custom hook.

**Comment by ondras** [comment]
@guybedford ah, interesting. Can you please point to me to the exact spec/place where I can read about the explicit extension usage? This is some important news to me.

**Comment by guybedford** [comment]
@ondras it is not mentioned specifically, but implied by the lack of a 'default js extension' being added anywhere.

**Comment by ondras** [comment]
Ah, okay, thanks.
