### ISSUE TITLE
How can I disable sourcemaps?

### ISSUE THREAD

**Issue by speigg** [ModuleLoader/es6-module-loader#418]
Trying to build with babel in jspm, with sourcemaps disabled. In my config.js: 

```js
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "sourceMaps": false
  }
});
```

But, es6-module-loader seems to be overwriting my options.

**Comment by guybedford** [comment]
There was a previous discussion around this in https://github.com/systemjs/systemjs/issues/295.

**Comment by speigg** [comment]
The issue is that the options I provide in "babelOptions" are being overriden, which is unexpected (it looks like the options for the other transpilers do the same). I can understand having "default" options for certain things if an option is not specified, but I don't think it makes sense for options that are explicitly provided by the developer to be overridden.

**Comment by speigg** [comment]
As discussed in the thread you mentioned, `System.sourceMaps = false` would be a nice way to set the *default* behavior, but the options that are passed into "babelOptions/traceurOptions" should take priority.

**Comment by guybedford** [comment]
Why would you want to disable source maps? For performance? Surely you need debugging though?

**Comment by guybedford** [comment]
Added in 0.17.4.
