### ISSUE TITLE
How to access transpiled module code?

### ISSUE THREAD

**Issue by dmail** [ModuleLoader/es6-module-loader#419]
Hello guys,

- Considering I'm creating a module to support sourcemap with es6 modules in nodejs
- Considering module sources are dynamcially transpiled

How would you access the generated code of the transpile function ? (see https://github.com/ModuleLoader/es6-module-loader/blob/master/src/transpiler.js#L27)

Currently I've modified the code as follow

```javascript
Loader.prototype.sources = {};
return self.sources[load.address] = 'var __moduleName = "' + load.name + '";' + transpileFunction.call(self, load, transpiler) + '\n//# sourceURL=' + load.address + '!transpiled';
```

Any chances you add something like that in a next build or should I maintain my own version with this hack?

**Comment by dmail** [comment]
I can't figure how but systemjs print the right stack trace. I'll switch to systemjs.

**Comment by guybedford** [comment]
@dmail it sounds like you're doing source map chaining here? Having an input source map loaded by the module loader and then used for the ES6 transpiling again?

**Comment by dmail** [comment]
@guybedford I'm sorry I don't understand your comment. Let me be more specific about my goal :

test.js
```javascript
throw new Error('test');
```

main.js
```javascript
var System = require('es6-module-loader').System;
System.import('./test.js').catch(console.log);
```

Running `node main.js` results in

```
Error: test
    at execute (file:///C:/Users/Documents/test.js!transpiled:8:13)
```

Instead of

```
Error: test
    at execute (file:///C:/Users/Documents/test.js:1:13)
```

To fix this I wanted to replace `file:///C:/Users/Documents/test.js!transpiled:8:13` by `file:///C:/Users/Documents/test.js:1:13`. In order to do that I need the source of `file:///C:/Users/Documents/test.js!transpiled` to read the sourcemap from it.

Do you see my point?

**Comment by guybedford** [comment]
Yes this is a limitation of source maps unfortunately, the error gets reported from the non-transpiled source. I have no idea why the engine does this actually. It's the same in Chrome, although breakpoints in the original untranspiled source will work completely fine too.

I think it's only working in SystemJS because it is running your code as a global hence not transpiling.

**Comment by dmail** [comment]
Exactly, and to print the right stack trace I need a pointer on the transpiled code. That's the point of my issue.

Can you explain me how SystemJS avoid to transpile the code. it seems impossible to me with my understanding of how babel/traceur work.

**Comment by guybedford** [comment]
As I said, it doesn't - it just isn't transpiling. Change your example to:

```javascript
throw new Error('test');
export var p = 5;
```

and you'd get the same issue with SystemJS. I believe this is a JavaScript engine limitation as far as I can tell.

**Comment by dmail** [comment]
Indeed SystemJS didn't transpile because I had no import/export statement in `test.js`. Thanks for the clarification and I confirm SystemJS behave like es6-module-loader.

I've published my repo at https://github.com/dmail/system-node-sourcemap.
You have to manually edit dist/es6-module-loader-dev.src.js to make it work as explained in the readme.

**Comment by dmail** [comment]
I've made a pull request #420
