### ISSUE TITLE
I can't loading ES6 Dynamically in the Browser since v0.17

### ISSUE THREAD

**Issue by k33g** [ModuleLoader/es6-module-loader#422]
Hello

With the v0.16.6, I could loading ES6 Dynamically in the Browser
(https://github.com/ModuleLoader/es6-module-loader/tree/v0.16.6#getting-started)
like that:

    <script src="js/vendors/browser.js"></script>
    <script src="js/vendors/es6-module-loader.js"></script>

    <script>
      System.transpiler = 'babel';
      System.import('js/index').then(function(module) {
        console.log("loaded.")
      }).catch(function (e) {
        console.error(e);
      });
    </script>

Since the v0.17 I've got an error when loading script
I use `es6-module-loader-dev.js` instead of   `es6-module-loader.js` as explained here https://github.com/ModuleLoader/es6-module-loader#getting-started

and I've got this in the browser console:

    GET http://localhost:8080/js/index 404 (Not Found)
    t       @ es6-module-loader-dev.js:7
    g.fetch @ es6-module-loader-dev.js:7
    g.fetch @ es6-module-loader-dev.js:7
    (anonymous function) @ es6-module-loader-dev.js:7

    Not Found: http://localhost:8080/js/index
      Error loading http://localhost:8080/js/index(anonymous function) @ (index):18
      
Regards
Philippe

**Comment by guybedford** [comment]
You need to include the file extension (`js/index.js`) as of the latest major version.

**Comment by k33g** [comment]
It works fine, thank you very much :+1:
