### ISSUE TITLE
Isomorphic module loading

### ISSUE THREAD

**Issue by PhilippMi** [ModuleLoader/es6-module-loader#425]
We have a single-page application and we do isomorphic server-side rendering with JSDOM to speed up the initial load, i.e. the page is rendered on the server using the same JavaScript code (including the es6-module-loader) and then the rendered HTML is delivered to the client.

The normal browser mode of the loader works perfectly inside JSDOM but the problem is that it loads modules using HTTP instead of file-based loading. I know that the loader uses file-based module loading when used inside a node application. We do have a node application but the loader [detects it as a browser application](https://github.com/ModuleLoader/es6-module-loader/blob/ed7fff2f342266ad7dc27d2f6d4fbd2035bec926/src/wrapper-start.js#L68-L84) since it also has a `document`.

My current workaround is to manually fake the baseURI to use `file:` protocol similar to what the loader would do in node.
```javascript
let indexHTML = ...; // contains a <script> to import SystemJS
jsdom.env({
    html: indexHTML,
    ...
    created: function(error, window) {
        // this is executed before any <script> inside indexHTML
        let isWindows = process.platform.match(/^win/);
        // fake baseURI for SystemJS
        let baseURI = 'file://' + (isWindows ? '/' : '')  + process.cwd() + '/';
        if (isWindows) {
            baseURI = baseURI.replace(/\\/g, '/');
        }
        window.document.__baseURI = window.document.baseURI;
        window.document.baseURI = baseURI;
        window.process = process;
    },
    done: function(errs, window) {
        // this is executed after <script> tags inside indexHTML
        // restore baseURI
        window.document.baseURI = window.document.__baseURI;
        ...
    }
});
```

So what it basically does is it takes the index.html and executes it inside the JSDOM sandbox and thereby emulating a browser. Before it executes any JavaScript inside index.html, we set up the `baseURI` to pretend to be file-based and restore it after the loader was initialized.

However, the solution is rather dirty because it may break with a future release of the es6-module-loader and abuses `document.baseURI`.

Do you have any suggestions on a better solution? Is there some other way to force the loader to use file-based module loading?

**Comment by guybedford** [comment]
The better solution to this kind of problem would be if you're able to run your rendering in Node without needing to use JSDOM. For example, React provides this kind of support. Then you can run the module loader via Node directly, which is set to use the file protocol automatically then for Node. It does rely on all rendering running through a rendering system like React that supports such a thing though. Otherwise what you're doing seems sensible to me.
