### ISSUE TITLE
Using es6-module-loader on precompiled js code (gulp-babel)

### ISSUE THREAD

**Issue by bensagardoy** [ModuleLoader/es6-module-loader#428]
I tried to use es6-module-loader on js files after my gulp process (gulp-babel) but i couldn't get rid off errors. It seems that it's obligatory to include a transpiler (traceur, babel etc.) inside html page before calling es6-module-loader script).

Is there an existing solution if we want to use es6 module loaders on already "babeled" files (ie with no runtime required) ?
Is there a project for a "gulp-es6-module-loader" in order to finally have only one working js file ?

**Comment by bensagardoy** [comment]
It seems that's it's better using Traceur (gulp-traceur to precompile), with the traceur-runtime js file, as it's described [here](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/production-workflows.md). 

But there are some problems again : System.import worked as expected, but 'classic' import didn't.

**Comment by guybedford** [comment]
There is a `system-register-only` build of SystemJS which just supports loading `System.register` modules and bundle files created by Traceur and other transpilers. There isn't much info available on how to set this up, so just let me know if you're having any problems at all.
