### ISSUE TITLE
How does TypeScript compilation work?

### ISSUE THREAD

**Issue by pspeter3** [ModuleLoader/es6-module-loader#429]
Does it load all of the files into the browser and then compile?

**Comment by mhegazy** [comment]
No. it does a simple file-level transpilation; which is in line with what the transpile hook is expected to do in System and ES6 module loader spec. 
TypeScript does not have type-directed emit. so the shape of the emitted code, in modules, does not depend on the compiler loading all files. 
This also means that you get no semantic errors in the browser. the assumption that you have got the errors through a different channel, i.e. your editor, and/or a full build step.

**Comment by mhegazy** [comment]
see [ts.transpile documentation](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function) for more informaiton

**Comment by pkozlowski-opensource** [comment]
@mhegazy just to make sure that I got it correctly: if I've got 2 files (say, foo.ts and bar.ts) it doesn't matter if I compile them together or separately, right? In this case, I wonder how types-checking works across files, ex.: 

in foo.js:

```javascript
import {Bar} from 'bar.js';

var bar = new Bar('some arg');
```

Given the above code snippet, it would meant that TS can't check constructor arg types for Bar, unless we include d.ts file for it. Is it correct?

//sorry for hijacking the thread, but I was dying to ask this question to someone familiar with TS inner working :-)

**Comment by maryo** [comment]
It simply skips the type checking, it only transpiles.

**Comment by mhegazy** [comment]
> It simply skips the type checking, it only transpiles.

that is correct.

knowing the types from your bar.ts is only needed to generate semantic errors in foo.ts. since you are not getting any errors any ways, there is no need to load bar.ts.
again the assumption is in your editor, or in a full build step, you will load both files, check your types and report all errors. in this workflow you are only interested in transpiling the code.

**Comment by guybedford** [comment]
@pspeter3 if you're looking for type checking support have a look at the SystemJS plugin https://github.com/frankwallis/plugin-typescript.

**Comment by pspeter3** [comment]
Thanks! I was just curious and appreciate you answering my question.
