### ISSUE TITLE
Babel option for module type isn't being specified

### ISSUE THREAD

**Issue by lyptt** [ModuleLoader/es6-module-loader#434]
When targeting babel as the ES6 transpiler via browser.js the module format isn't being exported properly. Instead babel's just using the default CommonJS format:

```javascript
(function() {
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var App = function App() {
  _classCallCheck(this, App);
};

exports["default"] = App;
module.exports = exports["default"];
//# sourceMappingURL={snip}
})
```

I'm using the `<script type="module"` syntax for registering my modules. Doing an explicit `System.import('{url}')` works fine.

Here's a plunker demonstrating the issue: http://plnkr.co/pz5XKkA8FNFrUeOAaZ4v

**Comment by lyptt** [comment]
Apologies, just noticed that this hasn't finished being implemented yet which is probably why it's going wrong. I assumed that because es6-module-loader's readme states it supports it that it was a completed feature. Maybe it's worth updating the readme if that's not the case?

**Comment by guybedford** [comment]
Yeah we don't support the `<script type="module" src="x">` syntax (implementation in https://github.com/ModuleLoader/es6-module-loader/blob/master/src/module-tag.js) as the spec is still not clear on this functionality. Perhaps Babel is handling this itself, and assuming CommonJS?
