### ISSUE TITLE
Perf test is failing on both the master branch and the 1.0 branch

### ISSUE THREAD

**Issue by joeldenning** [ModuleLoader/es6-module-loader#436]
At least for me it is. And not for performance reasons, but changes to the API.

Since `test:browser:perf` hasn't been updated in ~8 months and is not run as part of the `test` target, should it be removed? Or should the test be resurrected?

**Comment by guybedford** [comment]
Thanks for posting. It's definitely worth keeping around - shouldn't be too tricky to resurrect when needed again.
