### ISSUE TITLE
Usage example of dynamic modules in the instantiate hook

### ISSUE THREAD

**Issue by leizh** [ModuleLoader/es6-module-loader#438]
I can't figure how to handle the dependencies of the dynamic modules in the instantiate hook. I haven't found any example of this but I assume that the dependencies defined with `return { deps: ... }` must be executed before the current module. But I can't make it work.
For example, if I use this loader which reproduces the declarative modules in the demo , `System.get(test1Address)` is `undefined`:
```javascript
var test1Address = new URL('test1.js', document.baseURI).href;
System.instantiate = function (load) {
  if (!load.name) {
    return {
      deps: [ test1Address ],
      execute: function() {
        var hello = System.get(test1Address).hello;
        console.log(hello);
        return System.newModule({});
      }
    }
  } else if (load.name == test1Address) {
    return {
      execute: function() {
        return System.newModule({
          hello: 'world'
        })
      }
    }
  } else {
    return System.constructor.prototype.instantiate.call(this, load);
  }
}
```

Should I manually handle the dependencies in the `execute` method. In this case, what is the purpose of `deps` ?

**Comment by leizh** [comment]
A clarification: the dependencies are executed but after the calling module.

**Comment by guybedford** [comment]
Yes this is a result of the way cross-format circular execution works - the execute function is called unordered, with the assumption that the implementation must internally manage the execution ordering.

**Comment by guybedford** [comment]
Note that in the latest WhatWG step the dependencies are not even returned at all - all dependency execution management is done by the implementation.

**Comment by leizh** [comment]
Thanks for this explanation.
