### ISSUE TITLE
Non-deterministic error during deps load

### ISSUE THREAD

**Issue by mntnoe** [ModuleLoader/es6-module-loader#440]
I am randomly getting the following error:

    TypeError: Error loading "foo" at /path/to/foo.js
    Error loading "foo" from "bar" at /path/to/bar.js
    undefined is not an object (evaluating 'load.dependencies[i].value')

Inserting a log statement in the addLoadToLinkSet() function like this:

    console.log(load.dependencies);
    for (var i = 0, l = load.dependencies.length; i < l; i++) { ... }

Yields this result:

    [{key: 'angular', value: 'wrappers/angular'}, ..., undefined, ...]

I have experienced this error through the last 9 months, but only during unit test runs.

One possible explanation could be that the requestLoad() function is never resolved
 (15.2.4.6 ProcessLoadDependencies), or that a race condition occurs:

        for (var i = 0, l = depsList.length; i < l; i++) (function(request, index) {
          loadPromises.push(
            requestLoad(loader, request, load.name, load.address)

            // 15.2.4.6.1 AddDependencyLoad (load is parentLoad)
            .then(function(depLoad) {

              // adjusted from spec to maintain dependency order
              // this is due to the System.register internal implementation needs
              load.dependencies[index] = {
                key: request,
                value: depLoad.name
              };

In this case, `load.dependencies[index]` would not be have been set for the entry that is not resolved.

I need help figuring out why requestLoad() is not being resolved, though. Does anybody have any hints?

**Comment by guybedford** [comment]
This could well be a bug... do you mind if I ask which build tool are you using here?

**Comment by mntnoe** [comment]
It's a custom one, actually, as we have a lot of configuration management, but I use Broccoli.js for the build itself.

More info that might aid:

  - We use PhantomJS for running the unit tests.
  - We use SystemJS on top of ES6 Module Loader.
  - The error happens more often on files importing .json files using github.com/systemjs/plugin-json. At least I think so...

Any other info that could narrow it down?

**Comment by guybedford** [comment]
@mntnoe this does look like a bug from the original ES module loader spec that would need to be fixed in this pipeline.

SystemJS builder actually no longer uses the ES Module pipeline layer to do builds - we moved away to ensuring all modules are of the SystemJS register format within the pipeline.

Let me know if you are able to work around it, or if you need a fix, we can discuss possible approaches.

**Comment by mntnoe** [comment]
You're right. I was using an older version of the libraries, and forgot to check if I was using the newest version (duh). I have successfully migrated the code base to the most recent versions, have not encountered the bug since.

Sorry for the inconvenience, and thank you for your help :-)

**Comment by guybedford** [comment]
Thanks for reporting back, great to hear it is working.
