### ISSUE TITLE
nashorn support

### ISSUE THREAD

**Issue by mattkime** [ModuleLoader/es6-module-loader#444]
i took a peek at the code and it looks like it assumes its running in the browser or in node. how about nashorn support?

I'm new to this project and I'm curious if there's been any discussion around this.

**Comment by guybedford** [comment]
Nashorn support actually hasn't been considered to date, but could certainly be an option. The main APIs we need to access I believe are _readFile_, _eval_ and _cwd_. If the implementations of those are short enough not to bloat the codebase, then there's no reason not to support it.

**Comment by amitport** [comment]
please re-open
following https://github.com/systemjs/systemjs/issues/1113#issuecomment-193304506

**Comment by guybedford** [comment]
This specific project does not provide individual loader implementations, but this could be tracked at the system-register-loader project for example.

Also, you are welcome to construct your own loader with nashorn support based on the principles, and that would definitely be great to feed back into the projects here.
