### ISSUE TITLE
Using the module loader without a transpiler

### ISSUE THREAD

**Issue by kapitancho** [ModuleLoader/es6-module-loader#452]
As the current versions of the browsers support many ES6 features natively, it is already time to support the module loading without using any transpiler. I hope this feature will be implemented any time soon. Thanks!

**Comment by Reinmar** [comment]
:+1:

We're using only these features of ES6 which are already available in at least the browser that we use for coding. We plan to transpile the code only for production. So being able to use the loader without a transpiler would be great for development.

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/issues/579.
