### ISSUE TITLE
Problems with System.paths when System.normalize is overriden

### ISSUE THREAD

**Issue by Reinmar** [ModuleLoader/es6-module-loader#454]
I couldn't find anything about `System.paths` in the spec, so I assume that it's es6-module-loader's custom addition, hence reporting this here.

I've been playing with `System.normalize` to enable some smart mapping of paths. Namely, I want to hide an internal directory structure of a library so the library users won't need to know it.

The problem I faced was that if I normalize the path inside overridden `System.normalize`, then the user using `System.paths` needs to know that.

To give some code sample: https://github.com/ckeditor/ckeditor5-design/blob/es6modules-mapping-bug/index.html

The paths mapping won't work because the path does not start with `ckeditor5-*` but rather `node_modules/ckeditor5-*` as it was already normalised.

Now, I could move my code from `System.normalize` to `System.locate` and run it after `System.paths` was applied (as far as I understand it's applied in the original `System.locate`). However, I lose one important feature that I was hoping to use – the knowledge about the parent name or address (which is available in `System.normalize`).

The reason why I wanted to use parent name is that I want to be able to inject a module instead of some other module, but still make possible accessing the original module from the injected module (to allow extending it). Such mappings are possible with Require.JS and are very useful:

```
  require.config( {
        map: {
            '*': {
                'ui-library/button/view': 'ui-library-custom/button/view',
            },
            'ui-library-custom/button/view': {
                'ui-library/button/view': 'ui-library/button/view'
            }
        }
    } );
```

So in fact the issue could be generalised to how to map modules in the same way which is possible in Require.JS? Was I on the right track or is there another way?

**Comment by Reinmar** [comment]
> The reason why I wanted to use parent name is that I want to be able to inject a module instead of some other module, but still make possible accessing the original module from the injected module (to allow extending it). Such mappings are possible with Require.JS and are very useful:

I managed to do that with `System.normalize`: https://github.com/ckeditor/ckeditor5-design/blob/es6modules-injection/index.html#L26-L30. After exposing an API for this feature (could be a part of the lib I work on) it could be even usable, but it's a pity that this leaks to the user of the library (through the affected `System.paths`).

**Comment by guybedford** [comment]
Custom map config like this works fine through normalize and is supported in SystemJS by ensuring the map config always runs as the first step of normalize, before paths is applied. The other thing we do in SystemJS is to apply paths to the config itself, so that the configuration itself is normalized with paths applied to be in the same URL space.
