### ISSUE TITLE
shield.io badges

### ISSUE THREAD

**Issue by thisconnect** [ModuleLoader/es6-module-loader#459]
[![Dependencies](https://img.shields.io/david/ModuleLoader/es6-module-loader.svg?style=flat-square)](https://david-dm.org/ModuleLoader/es6-module-loader)
[![Dev Dependencies](https://img.shields.io/david/dev/ModuleLoader/es6-module-loader.svg?style=flat-square)](https://david-dm.org/ModuleLoader/es6-module-loader#info=devDependencies)

**Comment by guybedford** [comment]
Thanks for the suggestion. I don't think this should be a factor for new users of the project to consider though.
