### ISSUE TITLE
Should Map be used internally?

### ISSUE THREAD

**Issue by joeldenning** [ModuleLoader/es6-module-loader#461]
The latest commits by caridy in the spec start using Maps internally and also the Registry objects now have 8 functions that are pass-throughs to Map functions. Maps, of course, are not fully supported in any version of IE but are supported in the other major browsers.

What are your thoughts on depending on the es6-map polyfill at https://www.npmjs.com/package/es6-map? If not, then we should polyfill the following functions to act exactly like their `Map` counterparts?
```
Registry.prototype[Symbol.iterator]
Registry.prototype.entries
Registry.prototype.keys
Registry.prototype.values
Registry.prototype.get
Registry.prototype.set
Registry.prototype.has
Registry.prototype.delete
```

**Comment by guybedford** [comment]
Code size is a big concern for the loader, as it is part of the critical load path itself.

Looking at the polyfill implementation it seems to use quite a lot of dependencies etc.

The get, set, has, delete, keys and values outputs seem straightforward?

If it's possible to write the iterator and entries in a flexible way that can work in ES5, ES5 + polyfill, and ES6 I think that would be ideal, but I completely understand if it's a tough ask.

**Comment by joeldenning** [comment]
I'll give it a go
