### ISSUE TITLE
Throw when trying to edit a module export

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es6-module-loader#466]
In https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L760, we should be able to add a setter that just throws if trying to edit an export property.

**Comment by henrjk** [comment]
I had raised the question *Is it goal to have imports be immutable bindings? - Google Groups* and in response this issue was opened. 
Now I am having [second thoughts about this](https://groups.google.com/d/msg/jspm-io/yVR8a36CR9Q/Yl22IyStBQAJ). 

The main concern is that this change might break a lot of existing testing/mock code.

**Comment by guybedford** [comment]
@henrjk can you clarify why you think this would break testing code?

**Comment by henrjk** [comment]
The kind of thing I had in mind is:

```
--- file: settings.js
export let server = "example.com/foo" 
--- file: lib.js
import {server} from './settings'
<some code using server to be tested > 
--- file: test-lib
test lib.js with a 'test-server'
<use some magic code which would patch the `server` binding inside lib.js or perhaps any imports to `server`. Something akin to proxyquire >
```
Now dynamic System.import provides a module object and perhaps one could patch bindings there. For static imports one presumably would have to somehow hook into the loader to support this kind of patching for unit testing. 

Anyways I am a bit muddy on whether this is even an issue, but wanted to make sure there are no bad consequences. 








```

**Comment by guybedford** [comment]
Patching `import {server} from 'server'` is different to doing `import * as Server from 'server'`. It's only the latter case we can throw on for patches, the first case must be caught by static analysis in the transpilers themselves. Throwing in these cases at whatever levels are appropriate is important though to encourage specification compliance.

**Comment by guybedford** [comment]
Fixed in https://github.com/ModuleLoader/es6-module-loader/commit/cf0d2fb561d26e305f4fda9f3cf64d46033c27f0. Object.freeze performance seems to be good these days from what I can tell, which was the reservation here initially.
