### ISSUE TITLE
Which versions of Node to support / run tests on

### ISSUE THREAD

**Issue by joeldenning** [ModuleLoader/es6-module-loader#470]
Currently we do 0.10-0.12, and iojs. Can we drop support for any of those (especially since most are very old)? Also, we should potentially run the tests on a newer version of node (4.0 and/or 5.0). For reference, the long term support of all the versions of node can be found at https://github.com/nodejs/LTS/#lts-plan

One advantage of dropping support would make the CI testing a lot faster.

**Comment by guybedford** [comment]
Sure, an update to just 0.12, 4 and 5 sounds needed?
