### ISSUE TITLE
Cannot get es6-module-loader to work at all with node 4.3.0 and babel 6.5.1

### ISSUE THREAD

**Issue by ZiCog** [ModuleLoader/es6-module-loader#474]
I cannot for the life of me to get this to work with node. 4.3.0 (or 2.x.x) and babel 6.5.1

My test file, load.js:

    var System = require('es6-module-loader').System;
    System.transpiler = 'babel';
    System.import('some-module.js').then(function(m) {
        console.log(m.p);
     }).catch(function (err) {
        console.log(err);
    });

My module to load, some_module.js:

    export var p = 'NodeJS test';

Babel in the path as per the instructions:

    $ babel --version
    6.5.1 (babel-core 6.5.2)

The result of running it:

    $ node load.js 
    { [Error: Error loading file:///home/zicog/babel-es6-jsx-test/some-module.js
            Error loading file:///home/zicog/babel-es6-jsx-test/babel
            ENOENT: no such file or directory, open '/home/zicog/babel-es6-jsx-test/babel']
      errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      path: '/home/zicog/babel-es6-jsx-test/babel' }

Or if I change "some-module.js" to "some-module" as per the given example:

    $ node load.js 
    { [Error: Error loading file:///home/zicogl/babel-es6-jsx-test/some-module
            ENOENT: no such file or directory, open '/home/zicogl/babel-es6-jsx-test/some-module']
       errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      path: '/home/zicog/babel-es6-jsx-test/some-module' }

No idea if this is a bug or my error. Thanks for any help.

Edit: This does work with traceur if I remove the System.transpiler line. It does not work if I set the transpiler to typescript.

Is there a way to use this with no transpiler? Say when all the modules have been transpiled already.

**Comment by guybedford** [comment]
Yes, Babel 6 is not supported here. The transpiler layer here is being deprecated though for loaders like SystemJS to provide their own transpilers. See for example https://github.com/jspm/registry/blob/master/package-overrides/npm/engine.io-client%401.5.1.json.

**Comment by ZiCog** [comment]
Ah, is it so that I should  be using SystemJS then?

Sorry for the bother. Things change in JS/node/web land so fast I'm  dizzy.

**Comment by guybedford** [comment]
This is a lower-level project for loader development yes. SystemJS is more designed for standard use cases and workflows. You don't need to be on the edge if you don't want to be!

**Comment by ZiCog** [comment]
OK Thanks.

If I could not be pushing at the edges all the time I would have quit the computer business thirty years ago. No pain no gain as they used to say.

I do appreciate all you are doing.
