### ISSUE TITLE
String Literal Loading

### ISSUE THREAD

**Issue by joebrassi** [ModuleLoader/es6-module-loader#476]
What if I want to load a module like this:

```
<script>
  module = `   
    export class q {
      constructor() {
         console.log('this is an es6 class!');
      }
    }
  `;
  System.import(module).then(function(m) {
    new m.q();
  });
</script>
```

Is it possible? It seems not.

Reason of this approach: eventually one may receive the module in Json format from a HttpRequest.

**Comment by guybedford** [comment]
`System.define(name, source)` can be used for this case, although it is not heavily supported.

**Comment by joebrassi** [comment]
OK, I see. One last detail, could you please provide an example of this approach? As you said yourself, it is practically not supported (could not find any documentation)

**Comment by joebrassi** [comment]
...OK, I think I've found an example of it:

```
define('glow', function(require, exports, module) {
  return function glow() {
  };
});
```
According to this example, it seems to define a new module "glow", but the function imported is not a String literal, it is a hard-coded function. I just need to pass a String variable to the `System.import/define()` function so it can get the module. In fact, the feature I'm looking for is the (almost) very same `System.import()` but without downloading any file, because in the end, this function (`System.import()`) after downloading the `.js|.ts` file with the module to load, it is receiving a `String` which it uses to create and load the module, so it is the same with the only difference that I already downloaded the module over the `System.import()` behalf. Can you see my point? It is the very same function but without the file downloading. Is there any function that can do that?

Thank you.
