### ISSUE TITLE
What's difference between systemjs & es6-module-loader

### ISSUE THREAD

**Issue by sarbbottam** [ModuleLoader/es6-module-loader#482]
While searching for [dynamic import ES2015](https://www.google.com/?gws_rd=ssl#q=dynamic+import+ES2015), I came across [https://github.com/systemjs/systemjs/](https://github.com/systemjs/systemjs/) and [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)

Both seems to be serving similar purpose. Wondering what is the difference between them?

[Cross posted issue](https://github.com/systemjs/systemjs/issues/1196).

**Comment by guybedford** [comment]
Closing, as this is double-posted.
