### ISSUE TITLE
new Error() params swallow IE errors

### ISSUE THREAD

**Issue by npbenjohnson** [ModuleLoader/es6-module-loader#484]
```
new Error(msg, filename, linenumber)
```
Mdn labels filename and linenumber as non-standardized. In IE, when you pass more than one param, it evaluates the first param as a number, so the informational message becomes "undefined". This makes IE "use strict"; errors that aren't implemented in chrome / ff really hard to troubleshoot.

**Comment by tyrsius** [comment]
Here is the Microsoft documentation for the [Error class](https://msdn.microsoft.com/en-us/library/dww52sbt(v=vs.94).aspx), and here is [the offending use](https://github.com/ModuleLoader/es6-module-loader/blob/44df206d8ff2d446462a6ebde54925c63742d86a/src/wrapper-start.js#L53) in the module loader.

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/ModuleLoader/es6-module-loader/commit/1421c021f7f41c80c7623eaa6352cff800d76d82.

**Comment by tyrsius** [comment]
I am not sure that will solve the problem. Whether or not `filename` is present isn't dependent on whether or not its running in IE, so it could still try to call the 3 param version in IE

**Comment by guybedford** [comment]
`fileName` is a Mozilla-only error property.

**Comment by tyrsius** [comment]
Unless its coming from a custom error class

**Comment by guybedford** [comment]
I guess it does happen, sure I've added https://github.com/ModuleLoader/es6-module-loader/commit/0555305f0f3e22433838c1a7431126d255e4a1ce.

**Comment by tyrsius** [comment]
I think thats a lot safer. I was just about to recommend `var isIE = new Error('IETEST').description !== undefined`
