### ISSUE TITLE
System.importSync

### ISSUE THREAD

**Issue by Alphapage** [ModuleLoader/es6-module-loader#488]
Hello,

I think es6 module loader is only async because of ajax probably.
But when using with nodejs, is it possible to load code synchronously ?

My  goal is to achieve something like this:
```
import something from './myfile.js';
let path='./myfile.js'
const something2 = System.importSync(path);
```

Thanks in advance for your answers.

**Comment by guybedford** [comment]
A synchronous import API is not provided by the spec or this loader.
