### ISSUE TITLE
import and execution order

### ISSUE THREAD

**Issue by Alphapage** [ModuleLoader/es6-module-loader#505]
Hello,

It seems that each import in a .js file is running asynchronously.
For example, when:
```js
import {something} from './1.js'
console.log('inner execution)
import {something} from './2.js
debugger
import {something} from './3.js'
```
2 is called before 1 and debugger is reached after 3 was executed.

Any idea ? Maybe this is the correct behaviour to let import be asynchronous. I don't know a lot about the spec or maybe I'm wrong.

Thanks in advance for your help.

**Comment by probins** [comment]
imports are dependencies. You can define them where in the calling module you like, but they are 'hoisted' to the front. All dependencies are fetched and executed before any of the code in the calling module runs. If you want 1 to execute before 2, you need to make 1 a dependency of 2. Alternatively, make 1 and 2 define functions or classes, and then have your calling module execute the functions:
```
import {func1} from './1.js'
import {func2} from './2.js'
func1()
func2()
```

**Comment by Alphapage** [comment]
1.js
```
console.log('1')
```
2.js
```
console.log('2')
```
3.js
```
import './2.js'
console.log('3')
```
run.js
```
import './1.js'
import './2.js'
import './3.js'
```
Result = 
1
2
3

But it should be :
1 
2
2
3

Am I missing something ?

**Comment by probins** [comment]
imported modules are only executed once when first loaded.

**Comment by Alphapage** [comment]
You learn me something. Thank you vert much for your help.
