### ISSUE TITLE
Refreshed site for the project

### ISSUE THREAD

**Issue by addyosmani** [ModuleLoader/es6-module-loader#57]
@guybedford has done some incredible work taking this project further and I think it would help accelerate both testing and general usage by improving both our docs and the current site. I think the recent Traceur changes are worth making a splash about.

This could be something that might be worth exploring in Q1, 2014. I also think it would be useful to define what the goals for ModuleLoader are for next year. E.g:

Do we see ourselves as:

* A reference implementation that provides a stable, supported version of the draft work Mozilla has done on the loader spec?
* A reliable loader that we encourage other tools to build on and developers to use in their production apps - e.g JSPM has done a fantastic job building on the project and I could see others similarly switching over to using us.

Other questions:

* Do we want to push JSPM further as a part of these efforts and do we see it being ready for use in building either demoware or production-level apps too?. I think everyone that's seen it agrees its an amazing sister project, but don't feel its had (yet) the kind of uptake it could. What can we do to change that?

**Comment by guybedford** [comment]
Somehow it feels like this might not happen any time soon... :)
